### ISSUE TITLE
ccount example hangs...

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#139]
The output is:

```
Starting Deallocation..
2016-05-13 17:36:15,362: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2016-05-13 17:36:15,363: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2016-05-13 17:36:15,363: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "ccount.py", line 99, in <module>
    cluster.deallocate()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 117, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 304, in close
    pmgr.close (terminate=terminate)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 175, in close
    self.cancel_pilots()
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 579, in cancel_pilots
    self._worker.register_cancel_pilots_request(pilot_ids=pilot_ids)
  File "/home/antontre/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 608, in register_cancel_pilots_request
    time.sleep(0.3)
KeyboardInterrupt
Resource allocation cancelled.
```

**Comment by antonst** [comment]
This is on localhost

**Comment by vivek-bala** [comment]
I think this is a pilot shutdown issue. Similar to #147

**Comment by vivek-bala** [comment]
NA. Closing.
