### ISSUE TITLE
get_started fails

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.entk#146]
After all the installation steps that seem to work fine, I tried to run get_started, but that fails.
Maybe I'm misinterpreting the instructions, as it didn't appear I need to change something to be able to do this.

```
(myenv)[marksant@workflow scripts]$ RADICAL_ENTK_VERBOSE=REPORT python get_started.py

================================================================================
 EnsembleMD (0.4-RC0-23-g7974c73)                                               
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 1 instances of 1 stages on 1 allocated core(s) on 'local.localhost'   

Job waiting on queue...2016-05-14 14:17:37,057: radical.pilot       : MainProcess                     : PilotLauncherWorker-1: ERROR   : Using bootstrapper /home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh
Copying bootstrapper 'file://localhost/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/bootstrapper/bootstrap_1.sh' to agent sandbox (<saga.filesystem.directory.Directory object at 0x7f2bfb08b4d0>).
Copying sdist 'file://localhost/home/marksant/myenv/lib/python2.7/site-packages/radical/utils/radical.utils-0.40.tar.gz' to sandbox (file://localhost/home/marksant/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.marksant.016935.0000-pilot.0000/).
Copying sdist 'file://localhost/home/marksant/myenv/lib/python2.7/site-packages/saga/saga-python-0.40.2.tar.gz' to sandbox (file://localhost/home/marksant/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.marksant.016935.0000-pilot.0000/).
Copying sdist 'file://localhost/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/..//radical.pilot-0.40.2.tar.gz' to sandbox (file://localhost/home/marksant/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.marksant.016935.0000-pilot.0000/).
Writing agent configuration to file '/tmp/rp_agent_cfg_dirfDkL_b/agent_0.cfg'.
Copying agent configuration file 'file://localhost/tmp/rp_agent_cfg_dirfDkL_b/agent_0.cfg' to sandbox (file://localhost/home/marksant/radical.pilot.sandbox/rp.session.workflow.iu.xsede.org.marksant.016935.0000-pilot.0000/).
Pilot launching failed! (failed to run bootstrap: (127)(/bin/sh: /home/marksant/.saga/adaptors/shell_job/wrapper.sh: No such file or directory
) (/home/marksant/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +605 (initialize)  :  raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out))))
Traceback (most recent call last):
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 712, in run
    js = saga.job.Service(js_url, session=self._session)
  File "/home/marksant/myenv/lib/python2.7/site-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/home/marksant/myenv/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/home/marksant/myenv/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/home/marksant/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 507, in init_instance
    self.initialize ()
  File "/home/marksant/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py", line 605, in initialize
    raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out))
NoSuccess: failed to run bootstrap: (127)(/bin/sh: /home/marksant/.saga/adaptors/shell_job/wrapper.sh: No such file or directory
) (/home/marksant/myenv/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +605 (initialize)  :  raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out)))
2016-05-14 14:17:37,677: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2016-05-14 14:17:37,677: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2016-05-14 14:17:37,678: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
2016-05-14 14:17:37,954: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error during execution: .
Starting Deallocation..
2016-05-14 14:17:37,954: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error: .  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 312, in run
    plugin.execute_pattern(pattern, self)
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 100, in execute_pattern
    resource._pmgr.wait_pilots(resource._pilot.uid,'Active')
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 532, in wait_pilots
    time.sleep(0.5)
                                                              done 
```

**Comment by andre-merzky** [comment]
Mark, we hit that snafu several times over the last days - I am not yet sure whats up.  Can you please try again?  If that still fails, please remove ~/.saga/ and try once more.

For some reason, the shell adaptor's shell wrapper hickups, thus the bootstrap error on job service creation on localhost.

**Comment by marksantcroos** [comment]
Re-running actually helped. Didn't delete ~/.saga/

I'll leave it up to you to close this ticket or not then.

**Comment by andre-merzky** [comment]
thanks Mark.  I did not yet find the time to dig into that -- I assume its some job purging update in the wrapper which screws with old state, or something.  I'll try to iron this out before the release.

**Comment by mingtaiha** [comment]
Bump. I encountered this problem as well, and running again did not help.

**Comment by andre-merzky** [comment]
Thanks Ming.  Please try again after `rm -rf ~/.saga`!

**Comment by vivek-bala** [comment]
NA. We will have a round of testing of the current examples.
