### ISSUE TITLE
deallocation of 5.3.1 replica_exchange.py fails

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/radical.entk#147]
```
(myenv)[marksant@workflow examples]$ RADICAL_ENTK_VERBOSE=INFO python replica_exchange.py

...

Starting Deallocation..
2016-05-14 14:48:15,306: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2016-05-14 14:48:24,242: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Canceled
2016-05-14 14:48:24,243: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource allocation cancelled.
Resource allocation cancelled.2016-05-14 14:48:25,010: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource local.localhost state has changed to Failed
2016-05-14 14:48:25,010: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2016-05-14 14:48:25,010: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2016-05-14 14:48:25,011: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "replica_exchange.py", line 249, in <module>
    cluster.deallocate()
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 117, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/session.py", line 304, in close
    pmgr.close (terminate=terminate)
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 184, in close
    self._worker.cancel_launcher()
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 195, in cancel_launcher
    worker.stop ()
  File "/home/marksant/myenv/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 92, in stop
    self.join()
  File "/opt/radical/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/opt/radical/lib/python2.7/threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by vivek-bala** [comment]
I think this might be a pilot shutdown issue. I come across this sometimes too. Deallocation simply calls the pilot cancel function + some records some timestamps.

**Comment by vivek-bala** [comment]
Termination issues should be addressed in the latest RP. Will have a round of testing of current examples. Closing.
