### ISSUE TITLE
Issues running get_started.py

### ISSUE THREAD

**Issue by solejar** [radical-cybertools/radical.entk#149]
Running

```
RADICAL_ENTK_VERBOSE=REPORT python get_started.py
```

Produces:

```
================================================================================
 EnsembleMD (0.4-RC0-23-g7974c73)                                               
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 1 instances of 1 stages on 1 allocated core(s) on 'local.localhost'   

Job waiting on queue...2016-05-15 14:59:42,094: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2016-05-15 14:59:42,095: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2016-05-15 14:59:42,095: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/sean/myenv/local/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/sean/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
2016-05-15 14:59:42,286: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error during execution: .
Starting Deallocation..
2016-05-15 14:59:42,287: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error: .  File "/home/sean/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 312, in run
    plugin.execute_pattern(pattern, self)
  File "/home/sean/myenv/local/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 100, in execute_pattern
    resource._pmgr.wait_pilots(resource._pilot.uid,'Active')
  File "/home/sean/myenv/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 532, in wait_pilots
    time.sleep(0.5)
                                                              done 
```

Not sure if this is something wrong on my part.

**Comment by andre-merzky** [comment]
Hi Shawn, 

could you do me the favor and run the same test once more?  If that fails again, please do `rm -rf ~/.saga/` (on the target resource, or localhost if you try local), and then try again once more.  Several people stumbled over a SAGA update hiccup (which I still don't understand), I just want to make sure that isn't what you stumble over...

Thanks, Andre.

**Comment by vivek-bala** [comment]
NA. Closing.
