### ISSUE TITLE
ccount fails on Comet

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#151]
Hey,

Getting this:

```
2016-05-15 22:29:43,461: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.comet state has changed to Launching
2016-05-15 22:30:02,425: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.comet state has changed to PendingActive
2016-05-15 22:31:20,178: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.comet state has changed to Active
2016-05-15 22:31:20,762: radical.entk.bag_of_tasks.static.default: MainProcess                     : MainThread     : DEBUG   : Created stage_1 CU: {'kernel': None, 'executable': '/bin/bash', 'name': 'sta
ge_1', 'restartable': False, 'output_staging': [], 'stdout': None, 'pre_exec': [], 'mpi': False, 'environment': None, 'cleanup': False, 'arguments': ['-l', '-c', 'base64 /dev/urandom | head -c 1000000 > a
sciifile-16.dat'], 'stderr': None, 'cores': 1, 'post_exec': None, 'input_staging': []}.
2016-05-15 22:31:20,763: radical.entk.bag_of_tasks.static.default: MainProcess                     : MainThread     : INFO    : Submitted tasks for stage_1.
2016-05-15 22:31:29,861: radical.entk.bag_of_tasks.static.default: MainProcess                     : Thread-3       : ERROR   : Task with ID unit.000001 failed: STDERR: ssh_exchange_identification: Connec
tion closed by remote host
, STDOUT:  LAST LOG: push unit to agent after ftw staging
2016-05-15 22:31:29,861: radical.entk.bag_of_tasks.static.default: MainProcess                     : Thread-3       : ERROR   : Pattern execution FAILED.
2016-05-15 22:31:29,862: radical.pilot       : MainProcess                     : Thread-3       : ERROR   : unit manager controller thread caught system exit -- forcing application shutdown
Traceback (most recent call last):
  File "/home/iparask/EnMdTest2/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 262, in run
    self.call_unit_state_callbacks(unit_id, new_state)
  File "/home/iparask/EnMdTest2/lib/python2.7/site-packages/radical/pilot/controller/unit_manager_controller.py", line 199, in call_unit_state_callbacks
    cb(self._shared_data[unit_id]['facade_object'], new_state)
  File "/home/iparask/EnMdTest2/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 87, in unit_state_cb
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "/home/iparask/EnMdTest2/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 339, in execute_pattern
    resource._umgr.wait_units(uids)
  File "/home/iparask/EnMdTest2/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 698, in wait_units
    time.sleep (0.5)
KeyboardInterrupt
2016-05-15 22:31:30,259: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : INFO    : Deallocating Cluster
2016-05-15 22:31:34,712: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource xsede.comet state has changed to Canceled
2016-05-15 22:31:34,712: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : INFO    : Resource allocation cancelled.
```

Tell me what you need. I used debug.

**Comment by vivek-bala** [comment]
I have been getting the same for comet. Not sure why. I have pinged Andre about it, will have to wait for his comment.

**Comment by iparask** [comment]
Okay, continuing with the rest then

**Comment by andre-merzky** [comment]
Sorry, I have no idea what causes this... :/

**Comment by mingtaiha** [comment]
Bump. I encountered this too :(

**Comment by mingtaiha** [comment]
This works with the updated RP tutorial-xsede16 branch with the RP MongoDB Url. I'm for closing this ticket once Ioannis can confirm this.
