### ISSUE TITLE
Too many namespaces/collections (MongoDB)

### ISSUE THREAD

**Issue by mingtaiha** [radical-cybertools/radical.entk#161]
I get this error from time to time when I run one example right after another. Is there some delay in the MongoDB?

```
2016-07-13 15:08:11,469: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during resource allocation: too many namespaces/collections.
Traceback (most recent call last):
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 211, in allocate
    pmgr = radical.pilot.PilotManager(session=self._session)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 119, in __init__
    session=self._session)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 99, in __init__
    pilot_launcher_workers=pilot_launcher_workers
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/radical/pilot/db/database.py", line 174, in insert_pilot_manager
    result = self._pm.insert(pilot_manager_json)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/pymongo/collection.py", line 410, in insert
    _check_write_command_response(results)
  File "/home/mingtha/ve_entk/lib/python2.7/site-packages/pymongo/helpers.py", line 209, in _check_write_command_response
    raise OperationFailure(error.get("errmsg"), error.get("code"), error)
OperationFailure: too many namespaces/collections
Allocation failed: too many namespaces/collections
```

**Comment by vivek-bala** [comment]
Please try again with updated mongo url. Thanks

**Comment by mingtaiha** [comment]
I managed to run all the examples which have either ran successfully or failed due to some other error. I actually didn't see this error after I posted this issue :/

**Comment by mingtaiha** [comment]
I seem to no longer see this issue once I use the new MongoDB url. Close I guess?

**Comment by vivek-bala** [comment]
Yes, I don't expect to see this with rp url.

**Comment by vivek-bala** [comment]
This shows any time the DB is full. Simply need to clean the DB. Closing.
