### ISSUE TITLE
get_started.py fails on workflow machine with:

### ISSUE THREAD

**Issue by antonst** [radical-cybertools/radical.entk#165]
```
(ve_entk)[antontre@workflow scripts]$ python get_started.py 

================================================================================
 EnsembleMD (0.4.3-9-g13f4c7a)                                                  
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 1 instances of 1 stages on 1 allocated core(s) on 'local.localhost'   

Job waiting on queue...
Job is now running !
Waiting for stage_1 to complete.                                            done
--------------------------------------------------------------------------------
Pattern execution successfully finished                                         


Starting Deallocation..
Resource allocation cancelled.2016-07-13 15:54:46,887: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2016-07-13 15:54:46,887: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2016-07-13 15:54:46,887: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 258, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
Traceback (most recent call last):
  File "get_started.py", line 63, in <module>
    cluster.deallocate()
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 117, in deallocate
    self._session.close(cleanup=self._cleanup)
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/pilot/session.py", line 304, in close
    pmgr.close (terminate=terminate)
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 184, in close
    self._worker.cancel_launcher()
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 195, in cancel_launcher
    worker.stop ()
  File "/home/antontre/ve_entk/lib/python2.7/site-packages/radical/pilot/controller/pilot_launcher_worker.py", line 92, in stop
    self.join()
  File "/usr/lib64/python2.7/threading.py", line 950, in join
    self.__block.wait()
  File "/usr/lib64/python2.7/threading.py", line 339, in wait
    waiter.acquire()
KeyboardInterrupt
```

**Comment by vivek-bala** [comment]
This looks like a pilot shutdown issue (guess also requires better reporting), is this error repeating ?

**Comment by antonst** [comment]
I have only now realised that simulation actually finished. Can error handling be changed for tutorial purposes to hide this trace? since we know this happens on shutdown?

**Comment by antonst** [comment]
```
try:
    # shutdown
except:
    pass
```

**Comment by antonst** [comment]
Person giving this tutorial would sweat a bit less :-)

**Comment by vivek-bala** [comment]
I agree, but I think having a global try, except block would also hide other errors (or did I misunderstand your suggestion ?). I think separating/hiding this issue might be more appropriate in RP (or some flag from RP that tells us that the error is a shutdown issue).

**Comment by vivek-bala** [comment]
@andre-merzky thoughts/ideas ?

**Comment by antonst** [comment]
not global, just for shutdown

**Comment by antonst** [comment]
I guess you can place it even inside a global ```try/except``` and it still would show other exceptions above it

**Comment by antonst** [comment]
you can basically ignore anything raised by the ```deallocate``` call

**Comment by vivek-bala** [comment]
>
> you can basically ignore anything raised by the deallocate call
>
Yes ! That might be the simplest/quickest fix. Thanks !

**Comment by andre-merzky** [comment]
Agree with that approach...

**Comment by vivek-bala** [comment]
Termination should be reiterated in both RP and EnTK. Should have better reporting.
