### ISSUE TITLE
Local environment setup issue

### ISSUE THREAD

**Issue by Weiming-Hu** [radical-cybertools/radical.entk#186]
I was trying to run the first example on my desktop, but there seemed to be an error. When I ran `RADICAL_ENTK_VERBOSE=REPORT python2.7 pipeline_of_ensembles.py`, I got the following output:

```
================================================================================
 EnsembleMD (0.4.6)                                                             
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 16 instances of 1 stages on 2 allocated core(s) on 'local.localhost'  

Job waiting on queue...2017-03-12 11:15:13,681: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Resource error: 
2017-03-12 11:15:13,681: radical.entk.SingleClusterEnvironment: MainProcess                     : Thread-1       : ERROR   : Pattern execution FAILED.
2017-03-12 11:15:13,681: radical.pilot       : MainProcess                     : Thread-1       : ERROR   : sys.exit from callback
Traceback (most recent call last):
  File "/home/graduate/wuh20/Desktop/radical/lib/python2.7/site-packages/radical/pilot/controller/pilot_manager_controller.py", line 257, in call_callbacks
    cb(self._shared_data[pilot_id]['facade_object'](), new_state)
  File "/home/graduate/wuh20/Desktop/radical/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 168, in pilot_state_cb
    sys.exit(1)
SystemExit: 1
2017-03-12 11:15:13,685: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error during execution: .
Resulting checksums:

Starting Deallocation..
2017-03-12 11:15:13,687: radical.entk.SingleClusterEnvironment: MainProcess                     : MainThread     : ERROR   : Fatal error during execution: .
Fatal error: .  File "/home/graduate/wuh20/Desktop/radical/lib/python2.7/site-packages/radical/ensemblemd/single_cluster_environment.py", line 312, in run
    plugin.execute_pattern(pattern, self)
  File "/home/graduate/wuh20/Desktop/radical/lib/python2.7/site-packages/radical/ensemblemd/exec_plugins/bag_of_tasks/static.py", line 104, in execute_pattern
    resource._pmgr.wait_pilots(resource._pilot.uid,'Active')
  File "/home/graduate/wuh20/Desktop/radical/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 544, in wait_pilots
    time.sleep(0.5)
                                                              done 
```

Information on versions:
- Python2.7
- CentOS 6
- MongoDB 2.6.12

I have also created ~/.ssh/config file, following the steps on doc page 7. However, when I do `ssh mach1`, I got the following message:
` ssh: connect to host xxxxxxxx port 22: Connection timed out `
Not sure whether this led to the above error. Could anybody help me to fix this?

Just to add some more information, to connect to the mongo database, the username and password are needed. Where can I put them?

Many thanks from a newbie.....

**Comment by vivek-bala** [comment]
Hey @Weiming-Hu, since you are running locally the ssh connectivity shouldn't be an issue. 

Could you rerun the example with ```RADICAL_ENTK_VERBOSE=DEBUG RADICAL_PILOT_VERBOSE=DEBUG python pipeline_of_ensembles.py 2> verbose.log```? This will generate a lot of output and will be captured in verbose.log. Please attach the file here.

Regarding the mongo database, if you have this setup locally then you might need to user credentials. You will have to check the url to the driver is. The easier way would be to setup an account in ```www.mlab.com```, create a new database and a user (with a password) to that database. This will give you the url that can be used in the EnTK script. Let me know if you need help with the setup on mlab (this is much easier that installing mongodb on your machine).

**Comment by Weiming-Hu** [comment]
@vivek-bala Thank you. Mlab seems to be under maintenance right now. I will keep checking for updates.

I tried `RADICAL_ENTK_VERBOSE=DEBUG RADICAL_PILOT_VERBOSE=DEBUG python2.7 pipeline_of_ensembles.py 2> verbose.log`, and got the following stout:
```
================================================================================
 EnsembleMD (0.4.6)                                                             
================================================================================

Starting Allocation                                                            \
new session: [rp.session.sapphire.geog.psu.edu.wuh20.017238.0005]              \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
create pilot manager                                                          ok
create pilot description                                                      ok
submit 1 pilot(s) .                                                           ok
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
                                                                              ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 16 instances of 1 stages on 2 allocated core(s) on 'local.localhost'  

Job waiting on queue...                                                        \
wait for 1 pilot(s) -Fatal error during execution: .
Resulting checksums:

Starting Deallocation..
Fatal error: .closing session rp.session.sapphire.geog.psu.edu.wuh20.017238.0005
        \
close pilot manager                                                            \
wait for 1 pilot(s) -                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 64.9s                                                       ok
                                                                            done 
```

and here if the log file.

[verbose.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/838785/verbose.txt)

Thank you again.

**Comment by Weiming-Hu** [comment]
@vivek-bala it looks like the new session is created at my local machine (sapphire.geog.psu.edu) but the database is connected to mlab. Might be the problem?

**Comment by vivek-bala** [comment]
I think if you are using the database at mlab. It should be ok unless you have a firewall that blocks the connection. 

You should have a folder called ```radical.pilot.sandbox``` in your HOME folder. This should contain multiple folders with the names of the format ```rp.session.*```. Could you send me the contents of the latest rp.session.* folder please? 

The following should work if you are using bash:

```
cd $HOME/radical.pilot.sandbox
cd `ls -Art | tail -n 1`
```

**Comment by Weiming-Hu** [comment]
mlab is working now. I will go and create an account.

here is the contents of the folder.

Thank you.
[rp.session.sapphire.geog.psu.edu.wuh20.017238.0005-pilot.000.tar.gz](https://github.com/radical-cybertools/radical.ensemblemd/files/838830/rp.session.sapphire.geog.psu.edu.wuh20.017238.0005-pilot.000.tar.gz)

**Comment by vivek-bala** [comment]
So it looks like saga was not installed because of missing module.
```
Traceback (most recent call last):
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/download.py", line 628, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/util.py", line 598, in unpack_file
    untar_file(filename, location)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/util.py", line 521, in untar_file
    tar = tarfile.open(filename, mode)
  File "/home/graduate/wuh20/packages/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/graduate/wuh20/packages/lib/python2.7/tarfile.py", line 1770, in bz2open
    raise CompressionError("bz2 module is not available")
CompressionError: bz2 module is not available
```
I think bz2 is one of the standard modules that comes in the native python. I just noticed you are expliciting specifying ```python2.7``` while executing the scripts. What does ```python``` point to? 

Does the following work for you: ````python -c "import bz2"``` ?

**Comment by Weiming-Hu** [comment]
Yes, by default, CentOS has a python2.6 which does not meet ENTK requirements. So I built python2.7, and when I created the virtual environment I specified that I want to use python2.7. So there is an executable python2.7 in my environment.

I followed your instructions, and got the following:

**Comment by Weiming-Hu** [comment]
@vivek-bala 
```
(radical) [wuh20@sapphire radical]$ python -c "import bz2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named bz2
(radical) [wuh20@sapphire radical]$ python2.7 -c "import bz2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named bz2
(radical) [wuh20@sapphire radical]$ python2.7 -m pip install bz2
Collecting bz2
  Could not find a version that satisfies the requirement bz2 (from versions: )
No matching distribution found for bz2
```

**Comment by vivek-bala** [comment]
You might need to install python-dev, bz2 should be part of native-python though. You can do it with ```apt-get install python-dev```. Also what is the output of  ```python --version```?

**Comment by Weiming-Hu** [comment]
Here is some information about python version.

```
(radical) [wuh20@sapphire radical]$ python --version
Python 2.7.13
(radical) [wuh20@sapphire radical]$ deactivate 
[wuh20@sapphire radical]$ python --version
Python 2.6.6
```

I think I will need to compile dev as well. I don't have root admin in this machine, so I can't just do use apt-get or yum.

**Comment by vivek-bala** [comment]
Ah ok. You would have to upgrade the system python (outside the virtualenv) to python=2.7.* as well.

**Comment by Weiming-Hu** [comment]
@vivek-bala Hi Vivek. I have made a request and managed to upgrade my python. `bz2` package seems to work now.

```
[wuh20@sapphire examples]$ python --version
Python 2.7.8
[wuh20@sapphire examples]$ source ~/Desktop/radical/bin/activate
(radical)[wuh20@sapphire examples]$ python --version
Python 2.7.8
(radical)[wuh20@sapphire examples]$ python -c "import bz2"
(radical)[wuh20@sapphire examples]$ 
```

And then I tried the following command.
```
(radical)[wuh20@sapphire examples]$ RADICAL_ENTK_VERBOSE=DEBUG RADICAL_PILOT_VERBOSE=DEBUG python pipeline_of_ensembles.py 2> verbose.log
```

I got the following stout.
```
(radical)[wuh20@sapphire examples]$ RADICAL_ENTK_VERBOSE=DEBUG RADICAL_PILOT_VERBOSE=DEBUG python pipeline_of_ensembles.py 2> verbose.log

================================================================================
 EnsembleMD (0.4.6)                                                             
================================================================================

Starting Allocation                                                            \
new session: [rp.session.sapphire.geog.psu.edu.wuh20.017239.0001]              \
database   : [mongodb://rp:rp@ds015335.mlab.com:15335/rp]                     ok
create pilot manager                                                          ok
create pilot description                                                      ok
submit 1 pilot(s) .                                                           ok
create unit manager                                                           ok
add 1 pilot(s)                                                                ok
                                                                              ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 16 instances of 1 stages on 2 allocated core(s) on 'local.localhost'  

Job waiting on queue...                                                        \
wait for 1 pilot(s) /Fatal error during execution: .
Resulting checksums:

Starting Deallocation..
Fatal error: .closing session rp.session.sapphire.geog.psu.edu.wuh20.017239.0001
        \
close pilot manager                                                            \
wait for 1 pilot(s) -                                                         ok
                                                                              ok
close unit manager                                                            ok
session lifetime: 64.9s                                                       ok
                                                                            done 
```

And I have also attached the **rp.session** folder here.
[rp.session.sapphire.geog.psu.edu.wuh20.017239.0001-pilot.0000.tar.gz](https://github.com/radical-cybertools/radical.ensemblemd/files/840223/rp.session.sapphire.geog.psu.edu.wuh20.017239.0001-pilot.0000.tar.gz)

**Comment by Weiming-Hu** [comment]
@vivek-bala Just consulted technical support of Mlab, and they replied that for free sandbox I need to use mongo version 3.2, instead of 2.6.12. I think I might need to upgrade mongo as well. However, I am not sure whether CentOS supports the latest Mongo. I will find it out tomorrow.

According to the log information, do you think this would be the problem?

Good night!

**Comment by Weiming-Hu** [comment]
I switched to Mac OS Yosemite and tried again. It seems like it is working. Here is the output.

```

================================================================================
 EnsembleMD (0.4.6)                                                             
================================================================================

Starting Allocation                                                           ok
Verifying pattern                                                             ok
Starting pattern execution                                                    ok
--------------------------------------------------------------------------------
Executing 16 instances of 1 stages on 2 allocated core(s) on 'local.localhost'  

Job waiting on queue...    
Job is now running !
Waiting for stage_1 to complete.                                            done
--------------------------------------------------------------------------------
Pattern execution successfully finished                                         


Resulting checksums:
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt
  * da39a3ee5e6b4b0d3255bfef95601890afd80709  UTF-8-demo.txt

Starting Deallocation..
Resource allocation cancelled.                                              done 
```

Thank you!

**Comment by Weiming-Hu** [comment]
But I don't understand. It seems to be working even if I didn't configure the $HOME/.ssh/config file correct. Because I will get the error when I try to connect to mongodb:

```
Francesca:.ssh weiming$ ssh mach1
ssh_exchange_identification: read: Connection reset by peer
```

Below is the content:

```
Francesca:.ssh weiming$ cat config 
# contest of $HOME/.ssh/config

Host mach1
        HostName ds058579.mlab.com
        User weiming
        Port 58579
```

I have modified the **pipeline_of_ensembles.py**

```
cluster = ResourceHandle(
		resource=resource,
		cores=config[resource]["cores"],
		walltime=15,
		username=<username>,

		project=config[resource]['project'],
		access_schema = config[resource]['schema'],
		queue = config[resource]['queue'],
		database_url='mongodb://<username>:<password>@ds058579.mlab.com:58579/wuh20',
			)
```

Could you explain this to me? Thank you!

**Comment by vivek-bala** [comment]
Hey @Weiming-Hu ,

From "rp.session.sapphire.geog.psu.edu.wuh20.017239.0001-pilot.0000.tar.gz", it seems like the error is the same. Looking inside bootstrap_1.out :

```
Traceback (most recent call last):
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/basecommand.py", line 134, in main
    status = self.run(options, args)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/commands/install.py", line 236, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/req.py", line 1092, in prepare_files
    self.unpack_url(url, location, self.is_download)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/req.py", line 1238, in unpack_url
    retval = unpack_http_url(link, location, self.download_cache, self.download_dir)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/download.py", line 628, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/util.py", line 598, in unpack_file
    untar_file(filename, location)
  File "/home/graduate/wuh20/radical.pilot.sandbox/ve_localhost/lib/python2.7/site-packages/pip/util.py", line 521, in untar_file
    tar = tarfile.open(filename, mode)
  File "/home/graduate/wuh20/packages/lib/python2.7/tarfile.py", line 1693, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/home/graduate/wuh20/packages/lib/python2.7/tarfile.py", line 1770, in bz2open
    raise CompressionError("bz2 module is not available")
CompressionError: bz2 module is not available
```

Are you sure this is the correct rp.session folder?


> Just consulted technical support of Mlab, and they replied that for free sandbox I need to use mongo version 3.2, instead of 2.6.12. I think I might need to upgrade mongo as well. However, I am not sure whether CentOS supports the latest Mongo. I will find it out tomorrow.

I think there has been a misunderstanding here. If you are using mlab, you don't need to install mongodb on your local machine since the mongodb is hosted online. 

> But I don't understand. It seems to be working even if I didn't configure the $HOME/.ssh/config file correct. Because I will get the error when I try to connect to mongodb:

The ssh configuration is not to access mongodb. It is required to access another HPC (such as stampede) so that you can make the login passwordless. Since you are running the example locally on your machine, you do not need any ssh access and hence the example worked for you. I would suggest you to try the same on stampede next. Also, if you are using mlab, you already provide the username and password in the mlab url. 

Let me know if that makes sense/helps.

**Comment by Weiming-Hu** [comment]
@vivek-bala Thank you for your explanations. Now it's clear.

yes, you are right. I sent the wrong one. Sorry about that. I looked into the correct **bootstrap_1.out** and didn't find any error message. I think it now works on my Mac machine with mlab.

But when I switch back to CentOS, it failed again. I have attached **bootstrap_1.out** below.

[bootstrap_1.txt](https://github.com/radical-cybertools/radical.ensemblemd/files/844624/bootstrap_1.txt)

It looks like it is saying that `bz2 module is not available`. Because it is not possible to upgrade the bundle python2.6 in CentOS, so I installed a parallel python2.7 and the dev. I think it is probably because the program cannot find the right path because it is not the default path.

```
[wuh20@sapphire ~]$ which python
/opt/rh/python27/root/usr/bin/python
[wuh20@sapphire ~]$ python --version
Python 2.7.8
[wuh20@sapphire ~]$ python -c "import bz2"
[wuh20@sapphire ~]$ echo $PATH
/opt/rh/python27/root/usr/bin/:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/home/graduate/wuh20/bin
[wuh20@sapphire ~]$ echo $LD_LIBRARY_PATH 
/opt/rh/python27/root/usr/lib64/
[wuh20@sapphire ~]$ 
```

Is it helpful? Thank you!

**Comment by vivek-bala** [comment]
Yes, seems to be not able to load the bz2 module again. 

I am a bit confused. I can recommend the following:
* remove the alias
* Let's the say the path to the python executable which has bz2 is ```abc/xyz/python27/bin```, simply add this beginning of PATH: ```export PATH=/abc/xyz/python27/bin:$PATH```.
* Then test if ```python -c "import bz2"``` works. If so add the above export setting to your $HOME/.bashrc file (this might be $HOME/.bash_profile on some user accounts).

Basically, every command line executable you run is first searched for under PATH. If PATH points to multiple directories (such as in your and most cases), it picks the **first** executable it can find. Since it is important to prepend as opposed to append.

Let me know if this works/makes sense.

**Comment by vivek-bala** [comment]
I am assuming this was fixed since we got all AnEn scripts running for the experiments. Closing.
