### ISSUE TITLE
"Resource Request Submission Failed: Error in Appmanager"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#200]
EnTK 0.6 breaks with the following error. Please let me know if additional input is needed to help debug.

```
2018-02-01 19:52:57,829: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torqu[6/1880]
://bw.ncsa.illinois.edu]-[8139617] (old state: Pending, new state: Failed)
2018-02-01 19:53:04,504: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 stat
e: FAILED
2018-02-01 19:53:04,504: radical.entk.resource_manager: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-02-01 19:53:04,504: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-02-01 19:53:04,504: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 242, in run
    self._resource_manager._submit_resource_request()
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/entk/execman/resource_manager.py", line 344, in _submit_resource_requ$st
    raise Exception
Exception

wait for 1 pilot(s)
                                                                              ok
close pilot manager                                                            \
wait for 1 pilot(s)
                                                                         timeout
                                                                              ok
+ rp.session.two.scm177.017563.0005 (json)
2018-02-01 19:53:12,230: radical.utils       : MainProcess                     : MainThread     : DEBUG   : lm create  pool   for gsisftp://bw.ncsa.illinois$edu/shell_file_adaptor_command_shell/ (<type 'str'>) (<radical.utils.lease_manager.LeaseManager object at 0x7f7a08a96c90>)
2018-02-01 19:53:12,230: radical.utils       : MainProcess                     : MainThread     : DEBUG   : lm create  object for gsisftp://bw.ncsa.illinois$edu/shell_file_adaptor_command_shell/
2018-02-01 19:53:12,231: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : PTY prompt pattern: [\$#%>\]]\s*$
2018-02-01 19:53:12,231: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : ssh copy  mode set to 'sftp'
2018-02-01 19:53:12,231: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : ssh share mode set to 'auto'
2018-02-01 19:53:12,231: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : ssh timeout    set to '2000.0'
2018-02-01 19:53:12,232: radical.saga.pty    : MainProcess                     : MainThread     : INFO    : running: /usr/bin/env TERM=vt100 X509_USER_PROXY=
/tmp/x509up_u1011 /usr/bin/gsissh -t -o IdentityFile=/home/scm177/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_scm177_%h_%p.ctrl -o TCPKeep
Alive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=2000 bw.ncsa.illinois.edu
2018-02-01 19:53:16,276: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : init_instance gsisftp://bw.ncsa.illinois.edu/scra
tch/sciteam/mushnoor/radical.pilot.sandbox/rp.session.two.scm177.017563.0005/pilot.0000/bootstrap_1.prof
2018-02-01 19:53:16,493: radical.saga.cpi    : MainProcess                     : MainThread     : INFO    : file initialized (0)()
2018-02-01 19:53:16,595: radical.saga.pty    : MainProcess                     : MainThread     : INFO    : running: /usr/bin/env TERM=vt100 X509_USER_PROXY=
/tmp/x509up_u1011 /usr/bin/gsisftp -o IdentityFile=/home/scm177/.ssh/id_rsa -o ControlMaster=auto -o ControlPath=/tmp/saga_ssh_scm177_%h_%p.ctrl -o TCPKeepAl
ive=no -o ServerAliveInterval=10 -o ServerAliveCountMax=20 -o ConnectTimeout=2000 bw.ncsa.illinois.edu
+ pilot.0000 (profiles)
- pilot.0000 (logfiles)
session lifetime: 404.6s                                 
```

[Logfiles.gz](https://github.com/radical-cybertools/radical.entk/files/1690859/Logfiles.gz)

**Comment by kristofarkas** [comment]
I get the same error when running on Titan. There I am running EnTK locally. 

It hangs after `2018-02-02 09:32:36,343: radical.entk.resource_manager: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active` for some time, then gives the error:
```
2018-02-02 09:56:42,809: radical.entk.resource_manager: MainProcess                     : pmgr.0000.idler._state_pull_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-02-02 09:56:42,809: radical.entk.resource_manager: MainProcess                     : pmgr.0000.idler._state_pull_cb: ERROR   : Pilot has failed
2018-02-02 09:56:42,866: radical.entk.resource_manager: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-02-02 09:56:42,867: radical.entk.appmanager: MainProcess                     : MainThread     : ERROR   : Error in AppManager
```

**Comment by SrinivasMushnoori** [comment]
Increasing the number of nodes does not for me help on Blue Waters, unfortunately.

**Comment by vivek-bala** [comment]
Hey @SrinivasMushnoori , is this issue fixed. I remember there were some RP bootstrapping issues on BW. Is this issue a consequence of that.

**Comment by SrinivasMushnoori** [comment]
I believe this was addressed when the static ve creation fix was added to RP. Jobs on BW still fail, but that is because of https://github.com/radical-cybertools/radical.pilot/issues/1569 .

**Comment by vivek-bala** [comment]
Thanks for testing! Closing this ticket in that case.
