### ISSUE TITLE
attribute key / property name 'cores' is deprecated - use 'cpu_processes'

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#225]
The error I get is the following.
I changed all instances of "cores" to "cpu_processes" but I still get the error.

```
attribute key / property name 'cores' is deprecated - use 'cpu_processes'
2018-04-13 18:15:39,079: radical.entk.task_processor: task-manager                    : MainThread     : ERROR   : CU creation failed, error: attribute set is not extensib
le/private (key mpi) (/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.IncorrectState ("att
ribute set is not extensible/private (key %s)" %  key))
2018-04-13 18:15:39,079: radical.entk.task_manager.0000: task-manager                    : MainThread     : ERROR   : Task task.0000 submission failed, error: attribute se
t is not extensible/private (key mpi) (/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.Inc
orrectState ("attribute set is not extensible/private (key %s)" %  key))
```

My `radical-stack` is:

```
python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.6.1-entk-0.5-306-ga1887fc@devel
  radical.pilot        : 0.47.5-v0.47.5-153-g5bd24558@devel
  radical.utils        : 0.47.4-merge-pre_gpu-14-ga2181d6@devel
  saga                 : 0.47.3-merge-pre_gpu-24-g0fa0fb40@devel

```

**Comment by vivek-bala** [comment]
You are getting that error since you are using the gpu version of RP. I believe the devel branch got updated and you reinstalled RP from devel? You will have to use a non-gpu version of RP. @andre-merzky which branch do you recommend?

**Comment by SrinivasMushnoori** [comment]
Ok. I tried downgrading to master;
```
(EnTK0.6_env) scm177@two:~/RepEx3.0/src/radical/repex$ radical-stack

  python               : 2.7.12
  pythonpath           : 
  virtualenv           : /home/scm177/VirtualEnvs/EnTK0.6_env

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.6.1-entk-0.5-306-ga1887fc@devel
  radical.pilot        : 0.47.6-v0.47.6@master
  radical.utils        : 0.47.4-merge-pre_gpu-14-ga2181d6@devel
  saga                 : 0.47.3-merge-pre_gpu@master
```

The application runs, but all tasks fail because task sandboxes are empty.

**Comment by andre-merzky** [comment]
Can you please use the release for all layers then?  If you still see the same, please attach the pilot sandbox.

**Comment by SrinivasMushnoori** [comment]
Hi Andre
I am using master for SAGA and RP. I take it that by "release" you mean the master branch?
This is failing, because unit sandboxes are empty. Pilot sandbox is attached. Thanks!
[pilotsandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/1911304/pilotsandbox.tar.gz)

**Comment by SrinivasMushnoori** [comment]
Hi, this is what I found on the client logs:
```
2018-04-15 20:00:24,034: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : ERROR   : worker <bound method Default.work of <Default(umgr\
.0000.staging.input.0, started)>> failed
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1265, in work_cb
    self._workers[state](things)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 280, in work
    self._handle_unit(unit, actionables)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/umgr/staging_input/default.py", line 388, in _handle_unit
    if os.path.isdir(src.path):
AttributeError: 'str' object has no attribute 'path'
2018-04-15 20:00:24,034: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : DEBUG   : advance bulk size: 1 [False, True]
2018-04-15 20:10:47,453: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : ERROR   : abort: KeyboardInterrupt()
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/utils/process.py", line 625, in _run
    if not self.work_cb():
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1216, in work_cb
    things = input.get_nowait(1000) # timeout in microseconds
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 437, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 50, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 695, in poll
    evts = dict(p.poll(timeout))
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
    PyErr_CheckSignals()
KeyboardInterrupt
```

**Comment by andre-merzky** [comment]
Ah, I see, thanks!  Can you please try the radical.pilot branch `fix/issue_re_255` and report back if that resolves the issue?

**Comment by SrinivasMushnoori** [comment]
On it!

**Comment by SrinivasMushnoori** [comment]
No, it still fails. This is the new error:

```
2018-04-15 22:50:53,729: umgr.0000.staging.input.0.child: umgr.0000.staging.input.0       : MainThread     : ERROR   : abort: KeyboardInterrupt()
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/utils/process.py", line 625, in _run
    if not self.work_cb():
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 1216, in work_cb
    things = input.get_nowait(1000) # timeout in microseconds
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 437, in get_nowait
    if _uninterruptible(self._q.poll, flags=zmq.POLLIN, timeout=timeout):
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/radical/pilot/utils/queue.py", line 50, in _uninterruptible
    return f(*args, **kwargs)
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/zmq/sugar/socket.py", line 695, in poll
    evts = dict(p.poll(timeout))
  File "/home/scm177/VirtualEnvs/EnTK0.6_env/local/lib/python2.7/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc
    PyErr_CheckSignals()
KeyboardInterrupt

```
