### ISSUE TITLE
EnTK failed at Stage 3 on BW for 1300 CU job

### ISSUE THREAD

**Issue by kristofarkas** [radical-cybertools/radical.entk#231]
A large run on BW failed at stage 3/7, as in the next stage wasn't submitted due to errors. The logs show this error: 
 
```
Process task-manager:
Traceback (most recent call last):
  File "/home/kristofarkas/miniconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/kristofarkas/miniconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 418, in _tmgr
    raise Error(text=ex)
Error: Error: 'NoneType' object has no attribute 'poll'
Traceback (most recent call last):
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/radical/entk/execman/task_manager.py", line 406, in _tmgr
    self._mq_connection.close()
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 688, in close
    self._flush_output(self._closed_result.is_ready)
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 455, in _flush_output
    self._impl.ioloop.poll()
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 245, in poll
    self._poller.poll()
  File "/home/kristofarkas/miniconda2/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 923, in poll
    events = self._poll.poll(self._get_next_deadline())
AttributeError: 'NoneType' object has no attribute 'poll'

2018-05-19 06:47:47,493: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-05-19 06:47:47,493: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting task manager process from AppManager
2018-05-19 06:47:47,493: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : tmgr process already running, but attempted to restart!
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting heartbeat thread from AppManager
2018-05-19 06:47:47,494: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : Heartbeat thread already running, but attempted to restart!
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating heartbeat thread from AppManager
2018-05-19 06:47:47,494: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting task manager process from AppManager
2018-05-19 06:47:47,494: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : tmgr process already running, but attempted to restart!
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting heartbeat thread from AppManager
2018-05-19 06:47:47,495: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : Heartbeat thread already running, but attempted to restart!
2018-05-19 06:47:47,495: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating tmgr process from AppManager
2018-05-19 06:47:47,495: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-05-19 06:47:47,495: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting task manager process from AppManager
2018-05-19 06:47:47,495: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : tmgr process already running, but attempted to restart!
2018-05-19 06:47:47,495: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting heartbeat thread from AppManager
2018-05-19 06:47:47,495: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : Heartbeat thread already running, but attempted to restart!
2018-05-19 06:47:48,336: radical.saga.cpi    : umgr.0000.staging.input.0       : MainThread     : DEBUG   :  ===     5 : <saga.utils.pty_process.PTYProcess object at 0x7f83305246d0> : run async : QUIT
2018-05-19 06:47:48,337: radical.saga.pty    : umgr.0000.staging.input.0       : MainThread     : DEBUG   : flush: [  297] [     ] (flush pty read cache)
2018-05-19 06:47:48,337: radical.saga.pty    : umgr.0000.staging.input.0       : MainThread     : WARNING : flush: [  297] [    1] (discard data: '
')
2018-05-19 06:47:48,437: radical.saga.pty    : umgr.0000.staging.input.0       : MainThread     : DEBUG   : write: [  297] [    5] (QUIT\n)
2018-05-19 06:47:48,538: radical.saga.cpi    : umgr.0000.staging.input.0       : MainThread     : DEBUG   : PTYShell del  <saga.utils.pty_shell.PTYShell object at 0x7f830c0b91d0>
2018-05-19 06:47:48,538: radical.saga.pty    : umgr.0000.staging.input.0       : MainThread     : DEBUG   : PTYProcess del  <saga.utils.pty_process.PTYProcess object at 0x7f83305246d0>
2018-05-19 06:48:20,905: radical.saga.cpi    : pmgr.0000.launching.0           : Thread-2       : INFO    : Job monitoring thread updating Job [torque+gsissh://bw.ncsa.illinois.edu]-[8629749] (old state: Running, new state: Running)
```

Attached are all the files: [rp.session.two.kristofarkas.017669.0003.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2019301/rp.session.two.kristofarkas.017669.0003.tar.gz)

A similar job of smaller size finished successfully.

**Comment by kristofarkas** [comment]
The logs are here: https://github.com/kristofarkas/e-science-experiments/blob/master/exp-2/rfe.rp.session.log

**Comment by kristofarkas** [comment]
***Another note:*** During the first stage some of the runs fail due to a `No space left on device` error, which on Titan was due to too many concurrent `aprun` calls (Titan is limited to 50, here it was working for 300, fails at 1300). Does this mean that we have to switch to ORTE on BW too?

**Comment by kristofarkas** [comment]
@vivek-bala this specific error (warning) message comes up a lot, and do you know why/how it happens:
```
2018-05-19 06:47:47,493: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-05-19 06:47:47,493: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting task manager process from AppManager
2018-05-19 06:47:47,493: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : tmgr process already running, but attempted to restart!
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Restarting heartbeat thread from AppManager
2018-05-19 06:47:47,494: radical.entk.task_manager.0000: MainProcess                     : MainThread     : WARNING : Heartbeat thread already running, but attempted to restart!
2018-05-19 06:47:47,494: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating heartbeat thread from AppManager
2018-05-19 06:47:47,494: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
```

**Comment by kristofarkas** [comment]
Okay, part of the problem is that BW `aprun` supports only up to 400 concurrent CUs. Thanks @jdakka for pointing that out! I added a check for this in HTBAC, along with other similar checks that we know of (like the Titan 50).

Still, is the EnTK failure due to this? Tasks are submitted at Stage 2, two stages after the initial `aprun` failures.

**Comment by andre-merzky** [comment]
I think there are two different problems.  Your first message fails in pika - this looks like a communication problem to  RabbitMQ.  Vivek might be able to provide more insight once he is back online - but it might be worthwhile checking if your RMQ service is up and responsive.

The second problem is the `aprun` limit.  If you want to go beyond that limit, then you'll indeed need to switch to ORTE.  I can't say much about the relation of task numbers to stages though :/

**Comment by jdakka** [comment]
@kristofarkas the 400 concurrent CUs limit on Blue Waters is a lower bound of 2 sigma minus the avg. Regarding Titan, the issue we faced there if you remember was that ORNL had reduced the number of `aprun` permitted processes--this was not anticipated and we cannot plan for these circumstances, other than to switch launch methods. It may be that they change it again without notification.

**Comment by kristofarkas** [comment]
@jdakka what I meant is from a user perspective, as in to get an error *before* the job is submitted to the supercomputer, that this workload will not run (due to limitations for whatever reason).
