### ISSUE TITLE
Channel Closed Error from WFprocessor

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#240]
I am getting this error from the WF processor:
```
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 476, in _dequeue
    method_frame, header_frame, body = mq_channel.basic_get(queue=self._completed_queue[0])
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2032, in basic_get
    no_ack=no_ack)
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/channel.py", line 360, in basic_get
    self._validate_channel_and_callback(callback)
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/channel.py", line 1362, in _validate_channel_and_callback
    raise exceptions.ChannelClosed()
ChannelClosed
```

I will report again as I gather more information. Is there a chance I need to restart RabbitMQ?

**Comment by iparask** [comment]
Can you `cherry-pick` the fix in the  GPU branch as well?

**Comment by vivek-bala** [comment]
Actually, I would merge it rather than cherry pick. I have been merging and testing with the adaptivity branch. Next, going to merge and test against the GPU branch.

How frequent is that issue for you? Let me know what your time/deadline constraints are.

**Comment by iparask** [comment]
I believe every time I am running EnTK

**Comment by vivek-bala** [comment]
Fixed, tested in devel.

**Comment by vivek-bala** [comment]
Bump. Giannis, do you want to test this? If not, please close this is as the tests pass currently.

**Comment by iparask** [comment]
I haven't run any experiments with the new version of EnTK, as of now. I will close it and if I see it again I will reopen
