### ISSUE TITLE
"AttributeError: 'AppManager' object has no attribute 'resource_manager'" when invoking resource_terminate()

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#249]
Error:
```
Traceback (most recent call last):
  File "run.py", line 103, in <module>
    appman.resource_terminate()
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 479, in resource_terminate
    write_session_description(self)
  File "/home/scm177/VirtualEnvs/RepEx_RP_Devel/local/lib/python2.7/site-packages/radical/entk/utils/prof_utils.py", line 155, in write_session_description
    rmgr = amgr.resource_manager
AttributeError: 'AppManager' object has no attribute 'resource_manager'
```

`radical-stack`:
```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/RepEx_RP_Devel

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.0-0.7.0@master
  radical.pilot        : 0.50.4-v0.50.4-1-g6670e662@devel
  radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
  saga                 : 0.50.0-v0.50.0@devel

```

The RepEx(EnTK) script is here: https://github.com/SrinivasMushnoori/RepEx_3.0/blob/master/examples/run.py

**Comment by SrinivasMushnoori** [comment]
Hey @vivek-bala , is there anything else you require from me to resolve this?

**Comment by vivek-bala** [comment]
No, I think that should be enough. I know where the issue is coming from. I'll work on it tonight and patch it. Thanks!

**Comment by SrinivasMushnoori** [comment]
Hi @vivek-bala has there been an update regarding this issue?
Apologies, but this is blocking for me.
