### ISSUE TITLE
Pika channel closed error while running EnTK experiments

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#250]
When running on a Jetstream VM, I sometimes get the following error:
```
Synced task radical.entk.task.0005 with state DONE
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 476, in _dequeue
    method_frame, header_frame, body = mq_channel.basic_get(queue=self._completed_queue[0])
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2032, in basic_get
    no_ack=no_ack)
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/channel.py", line 360, in basic_get
    self._validate_channel_and_callback(callback)
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/pika/channel.py", line 1362, in _validate_channel_and_callback
    raise exceptions.ChannelClosed()
ChannelClosed
```
From EnTK's log file, I see the following:

```
2018-07-16 12:13:03,924: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-07-16 12:13:03,924: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : ERROR   : Unable to receive message from completed queue:
2018-07-16 12:13:03,924: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : ERROR   : Error in dequeue-thread:
2018-07-16 12:13:03,928: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/iparask/miniconda2/envs/EnTKGPU/lib/python2.7/site-packages/radical/entk/appman/wfprocessor.py", line 596, in _dequeue
    raise Error(text=ex)
Error: Error:

2018-07-16 12:13:03,954: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : DEBUG   : WFprocessor process terminated
2018-07-16 12:13:03,958: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-07-16 12:13:03,959: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
```

The stack used for this is:
```
  python               : 2.7.15
  pythonpath           :
  virtualenv           : EnTKGPU

  radical.analytics    : v0.45.2-102-gaec2e1d@devel
  radical.entk         : 0.6.1-0.6.0-31-g19668b3@feature-gpu
  radical.pilot        : 0.47.12-v0.47.12-172-g1f829fa@devel
  radical.utils        : 0.47.4-merge-pre_gpu-22-ga942c4b@devel
  saga                 : 0.47.4-v0.47.4-34-g61aec51@fix-issue_679
  pika                 : 0.11.2
```
The port used for RabbitMQ is `32773`

**Comment by vivek-bala** [comment]
Hey giannis, this pika issue should be resolved in the latest release. Can you install the latest version from pypi and try again?

**Comment by vivek-bala** [comment]
Bump. Giannis, do you want to test this? If not, please close this is as the tests pass currently.

**Comment by iparask** [comment]
Test run with the latest release do not show this error. Thank you!
