### ISSUE TITLE
mongo_db issues

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.entk#254]
I have several errors popping up after the tasks from the first stage complete: 

The first comes from the `task_processor.py` 

```
Process task-manager:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 270, in _tmgr
    raise Error(text=ex)
Error: Error: local variable 'resolved_placeholder' referenced before assignment
Traceback (most recent call last):
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 208, in _tmgr
    bulk_cuds.append(create_cud_from_task(t, placeholder_dict, local_prof))
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 277, in create_cud_from_task
    cud.input_staging = get_input_list_from_task(task, placeholder_dict)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 107, in get_input_list_from_task
    path = resolve_placeholders(path, placeholder_dict)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 74, in resolve_placeholders
    return resolved_placeholder
UnboundLocalError: local variable 'resolved_placeholder
[mongo_db.zip](https://github.com/radical-cybertools/radical.entk/files/2242355/mongo_db.zip)
' referenced before assignment
```

Then it appears that there is a mongo_db issue with the `re.session`

```
Process task-manager:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 270, in _tmgr
    raise Error(text=ex)
Error: Error: E11000 duplicate key error index: scalability.rp.session.two.jdakka.017742.0006.$_id_ dup key: { : "umgr.0000" }
Traceback (most recent call last):
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 176, in _tmgr
    umgr = rp.UnitManager(session=rmgr._session)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/pilot/unit_manager.py", line 148, in __init__
    self._session._register_umgr(self)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 781, in _register_umgr
    self._dbs.insert_umgr(umgr.as_dict())
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/pilot/db/database.py", line 354, in insert_umgr
    result = self._c.insert(umgr_doc)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pymongo/collection.py", line 410, in insert
    _check_write_command_response(results)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pymongo/helpers.py", line 202, in _check_write_command_response
    raise DuplicateKeyError(error.get("errmsg"), 11000, error)
DuplicateKeyError: E11000 duplicate key error index: scalability.rp.session.two.jdakka.017742.0006.$_id_ dup key: { : "umgr.0000" }
```

And lastly I get a callback error: 
 
```
Exception in thread heartbeat:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/radical/entk/execman/base/task_manager.py", line 151, in _heartbeat
    method_frame, props, body = mq_channel.basic_get(queue=self._hb_response_q)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_output
    self._impl.ioloop.poll()
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/base_connection.py", line 464, in _handle_read
    self._on_data_available(data)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/connection.py", line 2021, in _on_data_available
    self._process_frame(frame_value)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/connection.py", line 2142, in _process_frame
    if self._process_callbacks(frame_value):
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/connection.py", line 2123, in _process_callbacks
    frame_value)  # Args
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/home/jdakka/da_scheduler/venv/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1358, in _on_channel_closed
    method.reply_text)
ChannelClosed: (404, "NOT_FOUND - no queue 're.session.two.jdakka.017742.0005-hb-response' in vhost '/'")
```

```
radical.entk         : 0.7.3-0.7.3-3-g3080d2d@fix-issue_251
radical.pilot        : 0.50.4-v0.50.4-95-g208fd74e@project-DA-scheduler_algo
radical.utils        : 0.50.1-v0.50.1-1-gce60836@devel
saga                 : 0.50.0-v0.50.0@devel
```
client logs: 
[mongo_db.zip](https://github.com/radical-cybertools/radical.entk/files/2242356/mongo_db.zip)

agent logs on Blue Waters:
`~/scratch/radical.pilot.sandbox/rp.session.two.jdakka.017742.0006/pilot.0000`

**Comment by andre-merzky** [comment]
I can only speak for the MongoDB error (the second one): this seems to indicate that either EnTK tries to create two umgr instances with the same UID (which I doubt), or that the same RP session ID is used twice (more likely).  To confirm the either you could add a debug statement in `radical/pilot/db/database.py` before line 354, to see what session is how often registering that UMGR.  Please make sure that the session ID does not exist in the DB.

**Comment by jdakka** [comment]
The `mongodb` issue is part of ticket [255](
https://github.com/radical-cybertools/radical.entk/issues/255) but the first issue (placeholder issue) was resolved by changing the `task.name` to use only dashes.
