### ISSUE TITLE
Job fails after all tasks complete with "IOError: [Errno 2] No such file or directory: '/path/to/re.session.json'"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#257]
This is presumably while EnTK tries to read json files?
I should mention that I am running a profiling script after all tasks complete.
EnTK script is [here](https://github.com/SrinivasMushnoori/RepEx_3.0/blob/v3.0.0_rc1/repex/Sync.py)

```
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/bin/repex", line 5, in <module>
    pkg_resources.run_script('repex==3.0.1', 'repex')
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/pkg_resources.py", line 488, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/pkg_resources.py", line 1361, in run_script
    exec(script_code, namespace, namespace)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/repex-3.0.1-py2.7.egg/EGG-INFO/scripts/repex", line 108, in <module>

  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/analytics/session.py", line 92, in __init__
    self._description = re.utils.get_session_description(sid=sid, src=self._src)
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/entk/utils/prof_utils.py", line 217, in get_session_description
    desc = ru.read_json("%s/%s/%s.json" % (src, sid, sid))
  File "/home/scm177/VirtualEnvs/Env_RepEx/local/lib/python2.7/site-packages/radical/utils/read_json.py", line 26, in read_json
    with open (filename) as f:
IOError: [Errno 2] No such file or directory: '/home/scm177/RADICAL-LAB/RepEx_3.0/experiments/./re.session.mcewan.engr.rutgers.edu.scm177.017748.0016/./re.session.mcewan.engr.rutgers.edu.scm177.017748.0016.json'
```
If you observe the last line, there appears to be a typo in the path to the json.
Are there further logs you need? Happy to help debug.

**Comment by SrinivasMushnoori** [comment]
Oops, this appears to be a `radical.utils` issue....apologies. Pinging @andre-merzky
