### ISSUE TITLE
Task execution stops after Task 3625

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#268]
It's always Cycle 73 (Stage 146) that fails, and it fails only with 48 replicas. 24 replicas succeeds and runs to completion (80 cycles).48 replicas with 70 cycles also runs to completion. Now Cycle 73 fails because task 3626  (it's always 3626) does not even create a sandbox on the agent side. 3626 happens to be the "exchange" task of this cycle and causes the job to fail. 

If you look in the verbose logs, you will see something like:

```
Update: Task task.3621 in state SUBMITTED
2018-09-20 19:13:03,037: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.3621 to new state SUBMITTED successful
2018-09-20 19:13:03,037: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.3621 submitted to RTS
2018-09-20 19:13:03,038: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.3622 with state SUBMITTED
Update: Task task.3622 in state SUBMITTED
2018-09-20 19:13:03,039: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.3622 to new state SUBMITTED successful
2018-09-20 19:13:03,040: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.3622 submitted to RTS
2018-09-20 19:13:03,041: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.3623 with state SUBMITTED
Update: Task task.3623 in state SUBMITTED
2018-09-20 19:13:03,042: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.3623 to new state SUBMITTED successful
2018-09-20 19:13:03,043: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.3623 submitted to RTS
2018-09-20 19:13:03,044: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.3624 with state SUBMITTED
Update: Task task.3624 in state SUBMITTED
2018-09-20 19:13:03,045: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.3624 to new state SUBMITTED successful
2018-09-20 19:13:03,045: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.3624 submitted to RTS
2018-09-20 19:13:03,047: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.3625 with state SUBMITTED
Update: Task task.3625 in state SUBMITTED
2018-09-20 19:13:03,048: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Transition of task.3625 to new state SUBMITTED successful
2018-09-20 19:13:03,048: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task task.3625 submitted to RTS
2018-09-20 19:13:17,911: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-09-20 19:13:17,912: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-09-20 19:13:17,913: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2018-09-20 19:13:17,913: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response
2018-09-20 19:13:31,358: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-09-20 19:13:31,359: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: CANCELED
2018-09-20 19:13:31,360: radical.entk.wfprocessor.0073: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-09-20 19:13:31,361: radical.entk.wfprocessor.0073: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-09-20 19:13:31,364: radical.entk.wfprocessor.0073: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-09-20 19:13:31,365: radical.entk.wfprocessor.0073: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-09-20 19:13:31,381: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-09-20 19:13:31,381: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
Traceback (most recent call last):
  File "/home/scm177/VirtualEnvs/Env_RepEx/bin/repex", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/scm177/RADICAL-LAB/repex/bin/repex", line 94, in <module>
    Exchange_gen            = synchronousExchange.GeneralCycle(Replicas, Replica_Cores, Cycle, MD_Executable, ExchangeMethod)
  File "/home/scm177/RADICAL-LAB/repex/repex/Sync.py", line 263, in GeneralCycle
    'r') as f:  # Read exchangePairs.dat
IOError: [Errno 2] No such file or directory: 'exchangePairs_73.dat'
2018-09-20 19:13:47,913: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-09-20 19:13:47,913: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-09-20 19:13:47,914: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Received heartbeat request
2018-09-20 19:13:47,914: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Sent heartbeat response

```

`radical-stack` is:

```
  python               : 2.7.14
  pythonpath           :
  virtualenv           : /home/scm177/VirtualEnvs/Env_RepEx

  radical.analytics    : v0.45.2-103-g059830f@feature-entk-integration
  radical.entk         : 0.7.5-0.7.3-24-gf4030c3@devel
  radical.pilot        : 0.50.8-v0.50.8-6-g6e36785@devel
  radical.utils        : 0.50.1-v0.50.1-2-gfebbcd0@devel
  saga                 : 0.50.0-v0.50.0@devel
```

Tarball of verbose logs and RP profiles is [here.](https://github.com/radical-cybertools/radical.entk/files/2403436/debug.tar.gz) 
[Link](https://github.com/SrinivasMushnoori/repex/blob/devel/repex/Sync.py) to the EnTK script.

Let me know if I can provide assistance in debugging. 

Things I've tried:
1) Clearing MongoDB
2) Clearing RMQ/Docker instance

**Comment by SrinivasMushnoori** [comment]
Upon further investigation this has been found to be an issue internal to RepEx. One task in the middle takes FAR longer than it's supposed to to run to completion and causes stage 146 to stall indefinitely, causing the job to time out. Closing ticket since this has been identified as an issue in RepEx.
