### ISSUE TITLE
Invalid placeholder Error

### ISSUE THREAD

**Issue by iparask** [radical-cybertools/radical.entk#286]
I am using the devel branch of EnTK and I am getting the following error:

```
2018-12-06 11:29:44,753: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: DEBUG   : Attempting to sync task.0000 with state EXECUTED with AppManager
2018-12-06 11:29:44,768: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: DEBUG   : task.0000 with state EXECUTED synced with AppManager
2018-12-06 11:29:44,770: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: INFO    : Transition of task.0000 to new state EXECUTED successful
2018-12-06 11:29:44,773: radical.entk.task_manager.0000: task-manager                    : umgr.0000.subscriber._state_sub_cb: INFO    : Pushed task task.0000 with state EXECUTED to completed queue test_run_lfs_5-completedq-1
2018-12-06 11:29:44,843: radical.entk.task_manager.0000: task-manager                    : MainThread     : ERROR   : Error in task execution: Value for attribute placeholder of object length incorrect. Expected value $Pipeline_{pipeline.uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got [u'$NODE', u'LFS', u'PATH'].
Traceback (most recent call last):
  File "/home/iparask/miniconda2/envs/EnTKlfs/lib/python2.7/site-packages/radical/entk/execman/rp/task_manager.py", line 205, in _tmgr
    bulk_cuds.append(create_cud_from_task(t, placeholder_dict, local_prof))
  File "/home/iparask/miniconda2/envs/EnTKlfs/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 356, in create_cud_from_task
    cud.arguments = resolve_arguments(task.arguments, placeholder_dict)
  File "/home/iparask/miniconda2/envs/EnTKlfs/lib/python2.7/site-packages/radical/entk/execman/rp/task_processor.py", line 107, in resolve_arguments
    actual_value=broken_placeholder)
ValueError: Value for attribute placeholder of object length incorrect. Expected value $Pipeline_{pipeline.uid}_Stage_{stage.uid}_Task_{task.uid} or $SHARED, but got [u'$NODE', u'LFS', u'PATH'].
2018-12-06 11:31:07,849: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-12-06 11:32:14,231: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Received heartbeat response
2018-12-06 11:32:14,235: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
```

The part that generates the pipeline is:
```
 s0 = Stage()
    s0.name = '%s-S%s' % (name,0)
    # Create Task 1, training
    t0 = Task()
    t0.name = '%s-T0' % s0.name
    t0.pre_exec = ['module load psc_path/1.1',
                   'module load slurm/default',
                   'module load intel/17.4',
                   'module load python3',
                   'source $SCRATCH/pytorchCuda/bin/activate',
                   'hostname',
                   'echo $LOCAL',
                   'echo $NODE_LFS_PATH'
                  ]
    t0.executable = 'python3'   # Assign executable to the task
    # Assign arguments for the task executable
    t0.arguments = ['tile_raster.py','--scale_bands=%s'%tile_size,'--input_image=%s'%image.split('/')[-1],'--output_folder=$NODE_LFS_PATH/%s'%t0.name]
    t0.link_input_data = [image]
    t0.upload_input_data = ['tile_raster.py']
    t0.cpu_reqs = {'processes': 1,'threads_per_process': 1, 'thread_type': 'OpenMP'}
    t0.lfs_per_process = 1536

    s0.add_tasks(t0)
    # Add Stage to the Pipeline
    p.add_stages(s0)

    # Create a Stage object
    s1 = Stage()
    s1.name = '%s-S%s' % (name,1)
    # Create Task 1, training
    t1 = Task()
    t1.name = '%s-T1' % s1.name
    t1.pre_exec = ['module load psc_path/1.1',
                   'module load slurm/default',
                   'module load intel/17.4',
                   'module load python3',
                   'module load cuda',
                   'source $SCRATCH/pytorchCuda/bin/activate',
                   'hostname',
                   'export CUDA_VISIBLE_DEVICES=%d' % dev
                  ]
    t1.executable = 'python3'   # Assign executable to the task
    # Assign arguments for the task executable
    t1.arguments = ['predict_sealnet.py','--pipeline',pipeline,
                    '--dest_folder','./','--test_dir','$NODE_LFS_PATH/%s'%t0.name,'--model_architecture',model_arch,
                   '--hyperparameter_set',hyperparam_set,'--model_name',model_name,]
    t1.link_input_data = ['/pylon5/mc3bggp/paraskev/models/%s.tar' % model_name]
    t1.upload_input_data = ['predict_sealnet.py','utils/']
    t1.cpu_reqs = {'processes': 1,'threads_per_process': 1, 'thread_type': 'OpenMP'}
    t1.gpu_reqs = {'processes': 1,'threads_per_process': 1, 'thread_type': 'OpenMP'}
    t1.tag = t0.name

    s1.add_tasks(t1)
    # Add Stage to the Pipeline
    p.add_stages(s1)

    # Create a Stage object
    s2 = Stage()
    s2.name = '%s-S%s' % (name,2)
    # Create Task 2,
    t2 = Task()
    t2.pre_exec = ['module load psc_path/1.1',
                   'module load slurm/default',
                   'module load intel/17.4',
                   'module load python3',
                   'module load cuda',
                   'source $SCRATCH/pytorchCuda/bin/activate'
                  ]
    t2.name = '%s-T2' % s2.name
    t2.executable = ['python']   # Assign executable to the task
    # Assign arguments for the task executable
    t2.arguments = ['aggregate_predictions.py','%s_predictions.csv'%model_name]
    t2.upload_input_data = ['aggregate_predictions.py']
    for t in s1.tasks:
        t2.link_input_data = ['$Pipeline_%s_Stage_%s_Task_%s/%s_predictions.csv>%s_predictions.csv'%(p.uid, s1.uid, t.uid,model_name,t.name)]
    t2.download_output_data = ['%s_predictions.csv> %s_%s_predictions.csv'%(model_name,p.name,model_name)] #Download resuting images
    t2.cpu_reqs = {'processes': 1,'threads_per_process': 1, 'thread_type': 'OpenMP'}
    s2.add_tasks(t2)
    # Add Stage to the Pipeline
    p.add_stages(s2)
```

I do not understand where is the origin of the error.

**Comment by iparask** [comment]
It fails in the placeholder of the S2-T2 task

**Comment by iparask** [comment]
It seems to work. Any test I have executed is working as expected.

**Comment by vivek-bala** [comment]
Can this be closed? I can merge with master for the release.

**Comment by iparask** [comment]
Yes!
