### ISSUE TITLE
Fails on running get_started on comet

### ISSUE THREAD

**Issue by FreddieSun** [radical-cybertools/radical.entk#288]
After I logged into the jetstream atmosphere. I want to run the get_started example on Comet. Here is the get_started code after my modification. (I have lunched the rabbitmq by using docker and also specify the port number)

``` python
from radical.entk import Pipeline, Stage, Task, AppManager
import os

# ------------------------------------------------------------------------------
# Set default verbosity

if os.environ.get('RADICAL_ENTK_VERBOSE') == None:
    os.environ['RADICAL_ENTK_REPORT'] = 'True'

# Description of how the RabbitMQ process is accessible
# No need to change/set any variables if you installed RabbitMQ has a system
# process. If you are running RabbitMQ under a docker container or another
# VM, set "RMQ_HOSTNAME" and "RMQ_PORT" in the session where you are running
# this script.
hostname = os.environ.get('RMQ_HOSTNAME', 'localhost')
port = os.environ.get('RMQ_PORT', 32769)

if __name__ == '__main__':

    # Create a Pipeline object
    p = Pipeline()

    # Create a Stage object
    s = Stage()

    # Create a Task object
    t = Task()
    t.name = 'my-first-task'        # Assign a name to the task (optional, do not use ',' or '_')
    t.executable = ['/bin/echo']   # Assign executable to the task
    t.arguments = ['Hello World']  # Assign arguments for the task executable

    # Add Task to the Stage
    s.add_tasks(t)

    # Add Stage to the Pipeline
    p.add_stages(s)

    # Create Application Manager
    appman = AppManager(hostname=hostname, port=port)

    # Create a dictionary describe four mandatory keys:
    # resource, walltime, and cpus
    # resource is 'local.localhost' to execute locally
    res_dict = {
        'resource': 'xsede.comet',
        'walltime': 10,
        'cpus': 1,
	'project': 'unc100',
	'schema': 'gsissh',
    }

    # Assign resource request description to the Application Manager
    appman.resource_desc = res_dict

    # Assign the workflow as a set or list of Pipelines to the Application Manager
    # Note: The list order is not guaranteed to be preserved
    appman.workflow = set([p])

    # Run the Application Manager
    appman.run()
```

I got the ERROR information as follows:
```
EnTK session: re.session.js-17-147.jetstream-cloud.org.sun95.017877.0001
Creating AppManager                                                           ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                    ok
2018-12-11 19:59:19,743: radical.saga.pty    : MainProcess                     : MainThread     : ERROR   : prompted for unknown password (Password: ) (/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 315, in _initialize_pty
    % match)
AuthenticationFailed: prompted for unknown password (Password: ) (/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))
2018-12-11 19:59:19,743: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : ERROR   : Resource request submission failed
2018-12-11 19:59:19,744: radical.entk.appmanager.0000: MainProcess                     : MainThread     : ERROR   : Error in AppManager: prompted for unknown password (Password: ) (/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 309, in run
    self._resource_manager._submit_resource_request()
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 154, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 103, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/session.py", line 1020, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
AuthenticationFailed: prompted for unknown password (Password: ) (/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))
Traceback (most recent call last):
  File "get_started.py", line 60, in <module>
    appman.run()
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 309, in run
    self._resource_manager._submit_resource_request()
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 154, in _submit_resource_request
    self._pilot = self._pmgr.submit_pilots(pdesc)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/pilot_manager.py", line 502, in submit_pilots
    pilot = ComputePilot(pmgr=self, descr=pd)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/compute_pilot.py", line 103, in __init__
    self._resource_sandbox = self._session._get_resource_sandbox(pilot)
  File "/home/sun95/env/local/lib/python2.7/site-packages/radical/pilot/session.py", line 1020, in _get_resource_sandbox
    shell = rsup.PTYShell(js_url, self)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 247, in __init__
    interactive=self.interactive)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 198, in initialize
    self._initialize_pty (info['pty'], info)
  File "/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py", line 413, in _initialize_pty
    raise ptye.translate_exception (e)
saga.exceptions.AuthenticationFailed: prompted for unknown password (Password: ) (/home/sun95/env/local/lib/python2.7/site-packages/saga/utils/pty_shell_factory.py +315 (_initialize_pty)  :  % match))
```

My radical-stack is:
```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/sun95/env

  radical.entk         : 0.7.10
  radical.pilot        : 0.50.20
  radical.utils        : 0.50.2
  saga                 : 0.50.3

```

Any idea? Thanks

**Comment by vivek-bala** [comment]
Hey @FreddieSun , can you confirm if you can login to Comet from Jetstream without being prompted for a password?

**Comment by vivek-bala** [comment]
Ah okay. Please change ```'schema': 'gsissh'``` to ```'access_schema': 'gsissh'``` in the resource description.

**Comment by FreddieSun** [comment]
Thanks for your reply. Yes it works now. But I got the error like this.
```
EnTK session: re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003
Creating AppManager                                                           ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                    ok
2018-12-12 13:31:36,697: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
All components created
Update: Pipeline pipeline.0000 in state SCHEDULING
Update: Stage stage.0000 in state SCHEDULING
Update: Task task.0000 in state SCHEDULING
Update: Task task.0000 in state SCHEDULED
Update: Stage stage.0000 in state SCHEDULED
/home/sun95/env/local/lib/python2.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
All components terminated
```

For the code I only change the ` 'schema' ` to` 'access_schema' `like you said.

and here is the file of my EnTK session:
[re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2673267/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003.tar.gz)

Any idea? Thanks

**Comment by FreddieSun** [comment]
Thanks for your patient help.

1. I ran the `radical-pilot-fetch-logfiles re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003 ` under the directory $HOME/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003. A new dir re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003/ appear and inside it has the pilot.0000 folder which is still empty. Here is the re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003 file.
[re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2673491/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0003.tar.gz)

2. I run the script again with the 
```shell
export RADICAL_ENTK_VERBOSE=INFO

python get_started.py | tee verbose.log
```

Then I got the following info
```
2018-12-12 15:00:56,730: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 15:00:56,730: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 13092/MainThread
2018-12-12 15:00:56,731: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Application Manager initialized
2018-12-12 15:00:56,947: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 15:00:56,947: radical.entk.task_processor: MainProcess                     : MainThread     : INFO    :                      pid/tid: 13092/MainThread
2018-12-12 15:00:56,947: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 15:00:56,948: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 13092/MainThread
2018-12-12 15:00:56,948: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Created resource manager object: resource_manager.0000
2018-12-12 15:00:56,948: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource description validated
2018-12-12 15:00:56,948: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Workflow assigned to Application Manager
2018-12-12 15:00:57,373: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 15:00:57,374: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 13092/MainThread
2018-12-12 15:00:57,374: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Created WFProcessor object: wfprocessor.0000
2018-12-12 15:00:57,374: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting resource request submission
2018-12-12 15:01:08,383: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING_PENDING
2018-12-12 15:01:08,385: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Resource request submission successful.. waiting for pilot to go Active
2018-12-12 15:01:08,387: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: PMGR_LAUNCHING
2018-12-12 15:01:16,332: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-12-12 15:01:16,332: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
2018-12-12 15:01:16,401: radical.entk.resource_manager.0000: MainProcess                     : MainThread     : INFO    : Pilot is now active
2018-12-12 15:01:16,401: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting synchronizer thread
2018-12-12 15:01:16,402: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : synchronizer thread started
2018-12-12 15:01:16,402: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting WFProcessor process from AppManager
2018-12-12 15:01:16,405: radical.entk.wfprocessor.0000: MainProcess                     : MainThread     : INFO    : Starting WFprocessor process
2018-12-12 15:01:16,416: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : python.interpreter   version: 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]
2018-12-12 15:01:16,418: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    :                      pid/tid: 13092/MainThread
2018-12-12 15:01:16,423: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : WFprocessor started
2018-12-12 15:01:16,424: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Starting dequeue-thread
2018-12-12 15:01:16,425: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Dequeue thread started
2018-12-12 15:01:16,426: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Starting enqueue-thread
2018-12-12 15:01:16,429: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : enqueue-thread started
2018-12-12 15:01:16,456: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Created task manager object: task_manager.0000
2018-12-12 15:01:16,459: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Starting task manager process from AppManager
2018-12-12 15:01:16,460: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received pipeline.0000 with state SCHEDULING
2018-12-12 15:01:16,461: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found pipeline pipeline.0000, state SCHEDULING, completed False
2018-12-12 15:01:16,462: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Starting task manager process
2018-12-12 15:01:16,465: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of pipeline.0000 to new state SCHEDULING successful
2018-12-12 15:01:16,468: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0000 with state SCHEDULING
2018-12-12 15:01:16,468: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0000
2018-12-12 15:01:16,472: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of stage.0000 to new state SCHEDULING successful
2018-12-12 15:01:16,481: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Starting heartbeat thread
2018-12-12 15:01:16,485: radical.entk.task_manager.0000: task-manager                    : MainThread     : INFO    : Task Manager process started
2018-12-12 15:01:16,489: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating WFprocessor
2018-12-12 15:01:16,494: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SCHEDULING
2018-12-12 15:01:16,497: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating enqueue-thread
2018-12-12 15:01:16,497: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of task.0000 to new state SCHEDULING successful
2018-12-12 15:01:16,502: radical.entk.task_manager.0000: MainProcess                     : heartbeat      : INFO    : Sent heartbeat request
2018-12-12 15:01:16,503: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received task.0000 with state SCHEDULED
2018-12-12 15:01:16,506: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of task.0000 to new state SCHEDULED successful
2018-12-12 15:01:16,508: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Received stage.0000 with state SCHEDULED
2018-12-12 15:01:16,509: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: INFO    : Found parent pipeline: pipeline.0000
2018-12-12 15:01:16,510: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Transition of stage.0000 to new state SCHEDULED successful
2018-12-12 15:01:16,511: radical.entk.wfprocessor.0000: wfprocessor                     : enqueue-thread : INFO    : Enqueue thread terminated
2018-12-12 15:01:16,517: radical.entk.wfprocessor.0000: wfprocessor                     : MainThread     : INFO    : Terminating dequeue-thread
2018-12-12 15:01:16,518: radical.entk.wfprocessor.0000: wfprocessor                     : dequeue-thread : INFO    : Terminated dequeue thread
2018-12-12 15:01:16,521: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating synchronizer thread
2018-12-12 15:01:16,523: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Synchronizer thread terminated
2018-12-12 15:01:16,523: radical.entk.appmanager.0000: MainProcess                     : MainThread     : INFO    : Terminating task manager process
/home/sun95/env/local/lib/python2.7/site-packages/pymongo/topology.py:149: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
2018-12-12 15:01:42,873: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Task manager process closed
2018-12-12 15:01:46,509: radical.entk.task_manager.0000: MainProcess                     : MainThread     : INFO    : Hearbeat thread terminated
```
Then I ran the 
```
radical-pilot-fetch-logfiles re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005
```

Here is the session file for this run 


[re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2673521/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz)

**Comment by vivek-bala** [comment]
```
2018-12-12 15:01:16,332: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: INFO    : Pilot pilot.0000 state: FAILED
2018-12-12 15:01:16,332: radical.entk.resource_manager.0000: MainProcess                     : pmgr.0000.subscriber._state_sub_cb: ERROR   : Pilot has failed
```

That helps! Thank you for your patience.

Can you log into Comet and check under $HOME/radical.pilot.sandbox/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005? If it is not empty, can you add any files or folders available here please. That should have the error as it seems to be coming from the deployment on Comet.

**Comment by FreddieSun** [comment]
Here is the $HOME/radical.pilot.sandbox/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005/ folder in the Comet.

[re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz](https://github.com/radical-cybertools/radical.entk/files/2673666/re.session.js-17-147.jetstream-cloud.org.sun95.017877.0005.tar.gz)

Thanks

**Comment by FreddieSun** [comment]
Sure, thanks.
