### ISSUE TITLE
list() to str() incompatibility 

### ISSUE THREAD

**Issue by jdakka** [radical-cybertools/radical.entk#324]
Stack on Summit: 
```
  radical.entk         : 0.7.13
  radical.pilot        : 0.50.19-v0.50.19-101-g936422e@feature-summit_am
  radical.utils        : 0.50.3
  saga                 : 0.50.0-v0.50.0-22-g8c260f8@feature-summit
```

`d['executable']` error:

```
2019-03-04 18:35:46,706: radical.entk.appmanager.0000: MainProcess                     : synchronizer-thread: ERROR   : Unknown error in synchronizer: Expected (base) type(s) <type 'str'>, but got <type 'list'>..
 Terminating thread
Traceback (most recent call last):
  File "/ccs/home/jdakka/.conda/envs/snakes/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 888, in _synchronizer
    task_update(msg, '%s-sync-to-cb' % self._sid, props.correlation_id, mq_channel)
  File "/ccs/home/jdakka/.conda/envs/snakes/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 641, in task_update
    completed_task.from_dict(msg['object'])
  File "/ccs/home/jdakka/.conda/envs/snakes/lib/python2.7/site-packages/radical/entk/task/task.py", line 780, in from_dict
    actual_type=type(d['executable']))
TypeError: Expected (base) type(s) <type 'str'>, but got <type 'list'>.
```

I've changed my VE in `task.py` (line 780) to the following:

```
if 'executable' in d:
            if isinstance(d['executable'], (str, list)) or isinstance(d['executable'], unicode):
                self._executable = d['executable']
            else:
                raise TypeError(expected_type=str,
                                actual_type=type(d['executable']))

```
This solves the problem

**Comment by vivek-bala** [comment]
Thanks for the PR Jumana. Fixed and tested. Same as #295
