### ISSUE TITLE
EnTK (and other RCT packages) require Python 3 now?

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#369]
`pip install radical.entk` gives me the following error. But I see nothing in the documentation that asks for a uniform shift to P3.x, so I am hesitant to move to python 3.x. If it is indeed officially a P3.x package, I'm happy to upgrade everything.

```
(testing_entk_0.7)scm177@mcewan:~/VirtualEnvs$ pip install radical.entk
Downloading/unpacking radical.entk
  Downloading radical.entk-0.70.0.tar.gz (57kB): 57kB downloaded
  Running setup.py (path:/home/scm177/VirtualEnvs/testing_entk_0.7/build/radical.entk/setup.py) egg_info for package radical.entk
    
    warning: no files found matching '*.sh'
    warning: no files found matching '*.sh' under directory 'src'
    warning: no files found matching '*.json' under directory 'examples'
Downloading/unpacking radical.utils (from radical.entk)
  Downloading radical.utils-0.90.3.tar.gz (170kB): 170kB downloaded
  Running setup.py (path:/home/scm177/VirtualEnvs/testing_entk_0.7/build/radical.utils/setup.py) egg_info for package radical.utils
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/scm177/VirtualEnvs/testing_entk_0.7/build/radical.utils/setup.py", line 146, in <module>
        raise RuntimeError('%s requires Python 3.x (3.5 or higher)' % name)
    RuntimeError: radical.utils requires Python 3.x (3.5 or higher)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/scm177/VirtualEnvs/testing_entk_0.7/build/radical.utils/setup.py", line 146, in <module>

    raise RuntimeError('%s requires Python 3.x (3.5 or higher)' % name)

RuntimeError: radical.utils requires Python 3.x (3.5 or higher)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/scm177/VirtualEnvs/testing_entk_0.7/build/radical.utils
Storing debug log for failure in /home/scm177/.pip/pip.log
```

**Comment by mturilli** [comment]
What branch are you trying to install?

**Comment by SrinivasMushnoori** [comment]
I see. But this appears to be the case with saga too... `pip install radical.saga` also breaks with the same error.

**Comment by andre-merzky** [comment]
That should not happen.  There are Python-3 versions of RU and RS uploaded
to pypi indeed - but both should only be pulled when using Python-3.  Can
you send us the list of commands you used which lead to that error so that
I can try to reproduce it?  Thanks!

**Comment by SrinivasMushnoori** [comment]
I can confirm that this has been fixed. What needs to be done is apparently an explicit update of pip via 

`pip install --upgrade pip`

Sorry for the late response: juggling too many things. 
I completely wiped the old environments. Created fresh environments, explicitly upgaded pip and then the installation worked. Closing this ticket now, will reopen if necessary.
