### ISSUE TITLE
control.pubsub.bridge.0000 got unexpected message

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#386]
I'm getting an error on summit which happens only sometimes and is resolved when restarting.
```
EnTK session: re.session.login1.eh22.018205.0045
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
All components terminated
Error: control.pubsub.bridge.0000 got unexpected message (error: error("can't start new thread",)) [20.0]
Traceback (most recent call last):
  File "extasy_vamp.py", line 278, in <module>
    appman.run()
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 368, in run
    self._rmgr._submit_resource_request()
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 148, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/pilot/session.py", line 262, in __init__
    self._bridges    = ruc.start_bridges   (self._cfg, self, self._log)
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/pilot/utils/component.py", line 155, in start_bridges
    bridge = rpu_Pubsub(session, bname, rpu_PUBSUB_BRIDGE, bcfg_clone)
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/pilot/utils/pubsub.py", line 139, in __init__
    self.start()
  File "/ccs/home/eh22/.conda/envs/vampextasy/lib/python2.7/site-packages/radical/utils/process.py", line 567, in start
    (self._ru_name, msg, timeout))
RuntimeError: control.pubsub.bridge.0000 got unexpected message (error: error("can't start new thread",)) [20.0]
```

local session
[re.session.login1.eh22.018205.0045-local.zip](https://github.com/radical-cybertools/radical.entk/files/3811273/re.session.login1.eh22.018205.0045-local.zip)

no sandbox session

**Comment by euhruska** [comment]
```
radical-stack

  python               : 2.7.15
  pythonpath           : /sw/summit/xalt/1.1.4/site:/sw/summit/xalt/1.1.4/libexec
  virtualenv           : vampextasy

  radical.entk         : 0.72.1
  radical.pilot        : 0.73.1
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```
