### ISSUE TITLE
EnTK fails running on localhost with "se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key))"

### ISSUE THREAD

**Issue by SrinivasMushnoori** [radical-cybertools/radical.entk#395]
EnTK examples appear to be failing. Running with: 

```
RADICAL_LOG_LVL=debug
RADICAL_LOG_TGT=debug.log
```
Trace in `debug.log` is as follows (full file attached at the end):

```
Traceback (most recent call last):
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/engine/engine.py", line 185, in _load_adaptors
    adaptor_instance = adaptor_module.Adaptor ()
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/utils/singleton.py", line 35, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/adaptors/srm/srmfile.py", line 87, in __init__
    self.pty_url = self._cfg['pty_url']
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/utils/config.py", line 305, in __getitem__
    raise KeyError('no such key [%s]' % key)
KeyError: 'no such key [pty_url]'
```

In the terminal,

```
Traceback (most recent call last):
  File "poe.py", line 115, in <module>
    appman.run()
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 403, in run
    self._rmgr._submit_resource_request()
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 168, in _submit_resource_request
    pdesc = rp.ComputePilotDescription(pd_init)
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/pilot/compute_pilot_description.py", line 185, in __init__
    self.from_dict(from_dict)
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/attributes.py", line 2678, in from_dict
    self.set_attribute(k,v)
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/attributes.py", line 2332, in set_attribute
    return   self._attributes_i_set        (us_key, val, flow=_flow)
  File "/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/attributes.py", line 1068, in _attributes_i_set
    raise se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key)
radical.saga.exceptions.IncorrectState: attribute set is not extensible/private (key output_staging) (/home/srinivas/Virtual_Envs/repex_rct/local/lib/python2.7/site-packages/radical/saga/attributes.py +1068 (_attributes_i_set)  :  raise se.IncorrectState ("attribute set is not extensible/private (key %s)" %  key))
```

Unsure if the following helps/is related, but 
`ssh localhost` returns:
```
srinivas@IKELOS:~$ ssh localhost
ssh: connect to host localhost port 22: Connection refused
```
EDIT: reinstalling openssh fixed the above but the issue persists.

Stack is:

```
(repex_rct) srinivas@IKELOS:~/gits/radical.entk/examples/simple$ radical-stack

  python               : 2.7.15+
  pythonpath           : 
  virtualenv           : /home/srinivas/Virtual_Envs/repex_rct

  radical.entk         : 0.72.0-v0.72.0-55-g23c637f6@feature-stage_out
  radical.pilot        : 0.73.1-v0.73.1-3-ga8acaad5@master
  radical.repex        : 0.72.0-e16dbbf@devel
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```
Assistance is appreciated.
Zipped `debug.log` file:

[debug.zip](https://github.com/radical-cybertools/radical.entk/files/3952908/debug.zip)

Agent and client sandboxes with logs are below:

[client-sandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/3952913/client-sandbox.tar.gz)
[agent-sandbox.tar.gz](https://github.com/radical-cybertools/radical.entk/files/3952919/agent-sandbox.tar.gz)

**Comment by andre-merzky** [comment]
Hi @SrinivasMushnoori , the output staging branch is now also ported to Python3 - would you mind giving that a try?  We addressed the issues with the pty_url configuration there already.

**Comment by SrinivasMushnoori** [comment]
Will test today and get back to you.

**Comment by SrinivasMushnoori** [comment]
EnTK install is breaking. 
stack is here:
```
(rct_py3_2) srinivas@IKELOS:~/gits/radical.entk$ radical-stack

  python               : 3.6.9
  pythonpath           : 
  virtualenv           : /home/srinivas/Virtual_Envs/rct_py3_2

  radical.entk         : 0.90.6
  radical.pilot        : 0.90.8-v0.90.1-200-g0b6f81b3@tmp-am
  radical.saga         : 0.90.6
  radical.utils        : 0.90.8-v0.90.3-196-g0cad6bb@tmp-am
```

Install logs are [here](https://github.com/radical-cybertools/radical.entk/files/3984537/install_log.tar.gz)

**Comment by andre-merzky** [comment]
That install log does not seem to contain an error message beyond `error` - its somewhat difficult to say what's up :-(    The radical stack above though seems to indicate that entk is actually installed?  Not sure I understand that...

**Comment by SrinivasMushnoori** [comment]
It is installed, but not the `tmp-am` branch as you instructed via slack

**Comment by andre-merzky** [comment]
This has been fixed in the last SAGA release.
