### ISSUE TITLE
configuring RabbitMQ as a docker image 

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.entk#414]
I have rabbitmq downloaded and running as a docker container 
(venv) (base) nbp-135-141:user_guide abdullahghani$ docker ps 
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                 NAMES
f3edd55bf257        rabbitmq:3          "docker-entrypoint.s…"   27 hours ago        Up 27 hours         0.0.0.0:32771->4369/tcp, 0.0.0.0:32770->5671/tcp, 0.0.0.0:32769->5672/tcp, 0.0.0.0:32768->25672/tcp   rabbit

When I run the get_started.py script, it runs into the following error.

(venv) (base) nbp-135-141:user_guide abdullahghani$ python get_started.py 
EnTK session: re.session.nbp-143-221.nbp.ruw.rutgers.edu.abdullahghani.018289.0002
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.nbp-143-221.nbp.ruw.rutgers.edu.abdullahghani.018289.0002]
        \
database   : [mongodb+srv://entk:entk@cluster0-3njrj.mongodb.net/test?retryWrites=true&w=majority]
        err
All components terminated
Traceback (most recent call last):
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/session.py", line 173, in _initialize_primary
    cfg=self._cfg, log=self._log)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/db/database.py", line 58, in __init__
    self._mongo, self._db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/utils/misc.py", line 110, in mongodb_connect
    db.authenticate(user, pwd)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/pymongo/database.py", line 1471, in authenticate
    connect=True)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/pymongo/mongo_client.py", line 750, in _cache_credentials
    writable_preferred_server_selector)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/pymongo/topology.py", line 235, in select_server
    address))
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/pymongo/topology.py", line 193, in select_servers
    selector, server_timeout, address)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: cluster0-3njrj.mongodb.net:27017: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_started.py", line 61, in <module>
    appman.run()
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 414, in run
    self._rmgr._submit_resource_request()
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 148, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/session.py", line 147, in __init__
    self._initialize_primary(dburl)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/session.py", line 186, in _initialize_primary
    raise RuntimeError ('session create failed [%s]' % dburl)
RuntimeError: session create failed [mongodb+srv://entk:entk@cluster0-3njrj.mongodb.net/test?retryWrites=true&w=majority]

**Comment by lee212** [comment]
Support of docker image is no longer exist but I am happy to look at how we can support, if possible.

**Comment by Abdullah-Ghani** [comment]
Alternative solution of docker application worked perfectly fine. Thank you.
