### ISSUE TITLE
EnTK fails with 55K pipelines

### ISSUE THREAD

**Issue by AymenFJA** [radical-cybertools/radical.entk#422]
Hello @lee212 , 

We are trying to run near 55K pipelines on `XSEDE Bridges`, the EnTK crushes when it reaches `pipeline49603` and freeze on  `Update: Pipeline49603.KeyPoints_Generation.GPU-SIFT state: SUBMITTING`  for about an hour after that an exception rise with the following error :

```
  python               : 2.7.12
  pythonpath           :
  virtualenv           : /home/aymen/sift_env

  radical.analytics    : 0.72.1
  radical.entk         : 0.72.1
  radical.pilot        : 0.73.1
  radical.saga         : 0.72.1
  radical.utils        : 0.72.0
```
[entk.session-design1-64456.zip](https://github.com/radical-cybertools/radical.entk/files/4171727/entk.session-design1-64456.zip)

```
Exception in thread synchronizer-thread:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/aymen/sift_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 819, in _synchronizer
    self._synchronizer_work()
  File "/home/aymen/sift_env/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 890, in _synchronizer_work
    method_frame, props, body = mq_channel.basic_get(queue=qname_c2s)
  File "/home/aymen/sift_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/home/aymen/sift_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/home/aymen/sift_env/local/lib/python2.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
ConnectionClosed: (-1, "error(104, 'Connection reset by peer')")
```

**Comment by mturilli** [comment]
@AymenFJA, I am afraid you will have to move to the Python3 stack if you want to address this issue. The Python2 stack in a legacy mode so no further development is done on it.

**Comment by AymenFJA** [comment]
Thanks, @mturilli. Will investigate the issue further and migrate to py3 if it still exists I will reopen the ticket.
