### ISSUE TITLE
 connection to RabbitMQ lost

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#427]
extasy was running and multiple sessions worked as expected, but in one session I got error with possible rabbitMQ connection loss.  session zip:
[re.session.login1.eh22.018312.0006.zip](https://github.com/radical-cybertools/radical.entk/files/4232169/re.session.login1.eh22.018312.0006.zip)
error: 
```
Update: pipeline.0000.stage.0000.task.0040 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0041 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0042 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0043 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0044 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0045 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0046 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0047 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0048 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0049 state: SUBMITTING
Update: pipeline.0000.stage.0000.task.0050 state: SUBMITTING
submit 51 unit(s)
        ...................................................                   ok
close unit manager                                                            ok
Process task-manager:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 178, in _tmgr
    heartbeat_response(mq_channel)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 114, in heartbeat_response
    mq_channel.basic_get(queue=self._hb_request_q)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_output
    self._impl.ioloop.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 464, in _handle_read
    self._on_data_available(data)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2081, in _on_data_available
    self._process_frame(frame_value)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2202, in _process_frame
    if self._process_callbacks(frame_value):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2183, in _process_callbacks
    frame_value)  # Args
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1358, in _on_channel_closed
    method.reply_text)
pika.exceptions.ChannelClosed: (404, "NOT_FOUND - no queue 're.session.login1.eh22.018312.0006-hb-request' in vhost '/'")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 195, in _tmgr
    raise EnTKError(e)
radical.entk.exceptions.EnTKError: (404, "NOT_FOUND - no queue 're.session.login1.eh22.018312.0006-hb-request' in vhost '/'")
Process task-manager:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 144, in _tmgr
    mq_connection = pika.BlockingConnection(rmq_conn_params)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
    raise maybe_exception
pika.exceptions.ProbableAuthenticationError: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 195, in _tmgr
    raise EnTKError(e)
radical.entk.exceptions.EnTKError: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 206, in _tmgr
    mq_connection.close()
UnboundLocalError: local variable 'mq_connection' referenced before assignment
Exception in thread heartbeat:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/base/task_manager.py", line 249, in _heartbeat
    queue=self._hb_response_q)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_output
    self._impl.ioloop.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 464, in _handle_read
    self._on_data_available(data)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2081, in _on_data_available
    self._process_frame(frame_value)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2202, in _process_frame
    if self._process_callbacks(frame_value):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2183, in _process_callbacks
    frame_value)  # Args
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1358, in _on_channel_closed
    method.reply_text)
pika.exceptions.ChannelClosed: (404, "NOT_FOUND - no queue 're.session.login1.eh22.018312.0006-hb-response' in vhost '/'")
create unit manager/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pymongo/topology.py:155: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
                                                           ok
add 1 pilot(s)                                                                ok
close unit manager                                                            ok
Process task-manager:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 178, in _tmgr
    heartbeat_response(mq_channel)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 114, in heartbeat_response
    mq_channel.basic_get(queue=self._hb_request_q)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 458, in _flush_output
    self._impl.ioloop.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 495, in poll
    self._poller.poll()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 1114, in poll
    self._dispatch_fd_events(fd_event_map)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/select_connection.py", line 831, in _dispatch_fd_events
    handler(fileno, events)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 410, in _handle_events
    self._handle_read()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 464, in _handle_read
    self._on_data_available(data)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2081, in _on_data_available
    self._process_frame(frame_value)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2202, in _process_frame
    if self._process_callbacks(frame_value):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/connection.py", line 2183, in _process_callbacks
    frame_value)  # Args
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 60, in wrapper
    return function(*tuple(args), **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 92, in wrapper
    return function(*args, **kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/callback.py", line 236, in process
    callback(*args, **keywords)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1358, in _on_channel_closed
    method.reply_text)
pika.exceptions.ChannelClosed: (404, "NOT_FOUND - no queue 're.session.login1.eh22.018312.0006-hb-request' in vhost '/'")
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/execman/rp/task_manager.py", line 195, in _tmgr
    raise EnTKError(e)
radical.entk.exceptions.EnTKError: (404, "NOT_FOUND - no queue 're.session.login1.eh22.018312.0006-hb-request' in vhost '/'")
create unit manager/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pymongo/topology.py:155: UserWarning: MongoClient opened before fork. Create MongoClient only after forking. See PyMongo's documentation for details: http://api.mongodb.org/python/current/faq.html#is-pymongo-fork-safe
  "MongoClient opened before fork. Create MongoClient only "
                                                           ok
add 1 pilot(s)                                                                ok
Exception in thread dequeue-thread:
Traceback (most recent call last):
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/radical/entk/appman/wfprocessor.py", line 438, in _dequeue
    queue=self._completed_queue[0])
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/ccs/home/eh22/.conda/envs/vamp8/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (-1, "ConnectionResetError(104, 'Connection reset by peer')")
```
```
radical-stack

  python               : 3.7.3
  pythonpath           : /sw/summit/xalt/1.2.0/site:/sw/summit/xalt/1.2.0/libexec
  virtualenv           : vamp8

  radical.entk         : 0.90.6-v0.72.0-91-gb661847@devel
  radical.pilot        : 0.90.8-v0.90.1-224-gb7c5c6a@fix-issue_2022
  radical.saga         : 0.90.6-bv0.72.1-67-g5deb253@devel
  radical.utils        : 0.90.8-v0.90.3-192-g01c229d@devel
```

**Comment by lee212** [comment]
@euhruska , have you experienced this recently? I can't replicate and I'd like to close this if we can't see. and we can open later if this persist. Do you agree?

**Comment by euhruska** [comment]
not a current issue
