### ISSUE TITLE
pip install does not work for radical entk

### ISSUE THREAD

**Issue by aydinsaribudak** [radical-cybertools/radical.entk#432]
Hi,
`pip install .`  does not work in my virtual environment. Error message, radical-stack and virtualenv version information are below.

(ve-entk) aydins@js-17-94:~/radical.entk$ pip install .
Processing /home/aydins/radical.entk
    ERROR: Command errored out with exit status 1:
     command: /home/aydins/ve-entk/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-63fj_igs/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-63fj_igs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-63fj_igs/pip-egg-info
         cwd: /tmp/pip-req-build-63fj_igs/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-63fj_igs/setup.py", line 143, in <module>
        raise RuntimeError('%s requires Python 2.x (2.7 or higher)' % name)
    RuntimeError: radical.entk requires Python 2.x (2.7 or higher)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

radical-stack:
```
  python               : 3.7.6
  pythonpath           :
  virtualenv           : /home/aydins/ve-entk

  radical.analytics    : 0.90.7-v0.72.0-35-g4f5242d@devel
  radical.entk         : 1.0.0
  radical.pilot        : 1.0.0
  radical.saga         : 1.0.1
  radical.utils        : 1.0.0
```
virtualenv --version:
`16.7.4`

**Comment by lee212** [comment]
does the `python setup.py install` work instead?

**Comment by aydinsaribudak** [comment]
@lee212 thanks for the suggestion. Unfortunately it didnt work. Here is the error message:
(ve-entk) aydins@js-17-94:~/radical.pilot$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    raise RuntimeError('%s requires Python 2.x (2.7 or higher)' % name)
RuntimeError: radical.pilot requires Python 2.x (2.7 or higher)

**Comment by aydinsaribudak** [comment]
@lee212 My previous comment was from radical.pilot. Sorry about that. Here is the error I got for radical.entk:

(ve-entk) aydins@js-17-94:~/radical.entk$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 143, in <module>
    raise RuntimeError('%s requires Python 2.x (2.7 or higher)' % name)
RuntimeError: radical.entk requires Python 2.x (2.7 or higher)

**Comment by lee212** [comment]
This is probably old repo. The current `devel` has `3.6` at https://github.com/radical-cybertools/radical.entk/blob/92797c93e0e5c4aeb1e4f8c9947c1a2af1cf4870/setup.py#L143

please update your repo (`git pull`) and try again the installation.

**Comment by aydinsaribudak** [comment]
@lee212 I clear my folder from new files. Then I did git pull. But both `python setup.py install `and `pip install .` commands gave error messages. Sorry for the long error messages. 
```
(ve-entk) aydins@js-17-94:~/radical.entk$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from setuptools import setup, Command, find_packages
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
    import setuptools.version
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

```
(ve-entk) aydins@js-17-94:~/radical.entk$ git pull
Already up-to-date.

```
```
(ve-entk) aydins@js-17-94:~/radical.entk$ pip install .
Processing /home/aydins/radical.entk
    ERROR: Command errored out with exit status 1:
     command: /home/aydins/ve-entk/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-13uyee77/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-13uyee77/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-13uyee77/pip-egg-info
         cwd: /tmp/pip-req-build-13uyee77/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
```
(ve-entk) aydins@js-17-94:~/radical.entk$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    from setuptools import setup, Command, find_packages
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
    import setuptools.version
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
(ve-entk) aydins@js-17-94:~/radical.entk$ pip install .
Processing /home/aydins/radical.entk
    ERROR: Command errored out with exit status 1:
     command: /home/aydins/ve-entk/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-1hvgsrh0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-1hvgsrh0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-1hvgsrh0/pip-egg-info
         cwd: /tmp/pip-req-build-1hvgsrh0/
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/home/aydins/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by aydinsaribudak** [comment]
@lee212 After getting your suggestion I upgraded setuptools: `pip install --upgrade setuptools` and the issue is resolved. Thank you for taking care of this one. 
I am closing the issue.

```
(ve-entk) aydins@js-17-94:~/radical.entk$ pip install .
Processing /home/aydins/radical.entk
Requirement already satisfied: radical.utils in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.entk==1.0.1) (1.0.0)
Requirement already satisfied: radical.pilot in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.entk==1.0.1) (1.0.0)
Requirement already satisfied: pika==0.13.0 in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.entk==1.0.1) (0.13.0)
Requirement already satisfied: sphinx in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.entk==1.0.1) (2.3.1)
Requirement already satisfied: pymongo in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (3.10.1)
Requirement already satisfied: wheel in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (0.34.0)
Requirement already satisfied: msgpack in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (0.6.2)
Requirement already satisfied: pyzmq in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (18.1.1)
Requirement already satisfied: regex in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (2020.1.8)
Requirement already satisfied: munch in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (2.5.0)
Requirement already satisfied: colorama in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (0.4.3)
Requirement already satisfied: future in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (0.18.2)
Requirement already satisfied: netifaces in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (0.10.9)
Requirement already satisfied: setproctitle in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.utils->radical.entk==1.0.1) (1.1.10)
Requirement already satisfied: ntplib in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.pilot->radical.entk==1.0.1) (0.3.3)
Requirement already satisfied: msgpack-python in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.pilot->radical.entk==1.0.1) (0.5.6)
Requirement already satisfied: python-hostlist in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.pilot->radical.entk==1.0.1) (1.20)
Requirement already satisfied: radical.saga>=0.90 in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.pilot->radical.entk==1.0.1) (1.0.1)
Requirement already satisfied: sphinxcontrib-qthelp in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.0.2)
Requirement already satisfied: setuptools in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (45.2.0)
Requirement already satisfied: Jinja2>=2.3 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (2.10.3)
Requirement already satisfied: docutils>=0.12 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (0.16)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (0.7.12)
Requirement already satisfied: sphinxcontrib-htmlhelp in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.0.2)
Requirement already satisfied: requests>=2.5.0 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (2.22.0)
Requirement already satisfied: sphinxcontrib-applehelp in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.0.1)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (2.8.0)
Requirement already satisfied: sphinxcontrib-jsmath in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.0.1)
Requirement already satisfied: sphinxcontrib-devhelp in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.0.1)
Requirement already satisfied: packaging in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (20.1)
Requirement already satisfied: imagesize in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.2.0)
Requirement already satisfied: sphinxcontrib-serializinghtml in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (1.1.3)
Requirement already satisfied: snowballstemmer>=1.1 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (2.0.0)
Requirement already satisfied: Pygments>=2.0 in /home/aydins/ve-entk/lib/python3.7/site-packages (from sphinx->radical.entk==1.0.1) (2.5.2)
Requirement already satisfied: six in /home/aydins/ve-entk/lib/python3.7/site-packages (from munch->radical.utils->radical.entk==1.0.1) (1.14.0)
Requirement already satisfied: parse in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.saga>=0.90->radical.pilot->radical.entk==1.0.1) (1.14.0)
Requirement already satisfied: apache-libcloud in /home/aydins/ve-entk/lib/python3.7/site-packages (from radical.saga>=0.90->radical.pilot->radical.entk==1.0.1) (2.8.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/aydins/ve-entk/lib/python3.7/site-packages (from Jinja2>=2.3->sphinx->radical.entk==1.0.1) (1.1.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/aydins/ve-entk/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk==1.0.1) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/aydins/ve-entk/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk==1.0.1) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/aydins/ve-entk/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk==1.0.1) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in /home/aydins/ve-entk/lib/python3.7/site-packages (from requests>=2.5.0->sphinx->radical.entk==1.0.1) (2.8)
Requirement already satisfied: pytz>=2015.7 in /home/aydins/ve-entk/lib/python3.7/site-packages (from babel!=2.0,>=1.3->sphinx->radical.entk==1.0.1) (2019.3)
Requirement already satisfied: pyparsing>=2.0.2 in /home/aydins/ve-entk/lib/python3.7/site-packages (from packaging->sphinx->radical.entk==1.0.1) (2.4.6)
Building wheels for collected packages: radical.entk
  Building wheel for radical.entk (setup.py) ... done
  Created wheel for radical.entk: filename=radical.entk-1.0.1-py3-none-any.whl size=517539 sha256=51c8ce521c57a6f31b469fd3c809f601b022393a0f8fc353da132f1bbacf91fb
  Stored in directory: /tmp/pip-ephem-wheel-cache-i_tssp1a/wheels/dc/9c/2f/240e25ea391aabaaf13853f44b8641090b4650780c2abd8946
Successfully built radical.entk
Installing collected packages: radical.entk
  Attempting uninstall: radical.entk
    Found existing installation: radical.entk 1.0.0
    Uninstalling radical.entk-1.0.0:
      Successfully uninstalled radical.entk-1.0.0
Successfully installed radical.entk-1.0.1
```
