### ISSUE TITLE
Making EnTK work on other HPC systems (Amarel)

### ISSUE THREAD

**Issue by Abdullah-Ghani** [radical-cybertools/radical.entk#438]
I am using the below resource config file.

```
# filename: rutgers.json
{
"amarel":
{
        "description"                 : "The Amarel HPC cluster at Rutgers.",
        "notes"                       : "Access from registered IP address.",
        "schemas"                     : ["ssh","local"],
        "ssh"                         :
        {
            "job_manager_endpoint"    : "slurm+ssh://aag193@amarel.rutgers.edu/",
            "filesystem_endpoint"     : "sftp://aag193@amarel.rutgers.edu/home/aag193/"
        },
        "local"                       :
        {
            "job_manager_endpoint"    : "slurm://amarel.rutgers.edu:/home/aag193/",
            "filesystem_endpoint"     : "file://amarel.rutgers.edu:/home/aag193/"
        },
        "default_queue"               : "main",
        "resource_manager"            : "SLURM",
        "agent_scheduler"             : "CONTINUOUS",
        "agent_spawner"               : "POPEN",
        "agent_launch_method"         : "SSH",
        "task_launch_method"          : "SSH",
        "mpi_launch_method"           : "srun",
        "pre_bootstrap_0"             :["module load gcc/5.4",
                                        "module load intel/17.0.4",
                                        "module load python/3.5.2"
                                        ],
        "default_remote_workdir"      : "/home/aag193",
        "valid_roots"                 : ["/scratch", "$SCRATCH", "/home", "$HOME"],
        "rp_version"                  : "local",
        "virtenv_mode"                : "create",
        "python_dist"                 : "default",
        "export_to_cu"                : ["LMOD_CMD",
                                         "LMOD_SYSTEM_DEFAULT_MODULES",
                                         "LD_LIBRARY_PATH"],
        "cu_pre_exec"                 : ["module restore"]
    }
}
```

The EnTK getting started script runs into the following errors.

```
(venv) nbp-133-99:re.session.nbp-137-149.nbp.ruw.rutgers.edu.abdullahghani.018337.0000 abdullahghani$ grep ERROR *.*
pmgr.0000.log:1584375232.365 : pmgr.0000            : 73333 : 123145557733376 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
pmgr.0000.log:1584375232.366 : pmgr.0000            : 73333 : 123145557733376 : ERROR    : listener died
radical.entk.appmanager.0000.log:1584375232.439 : radical.entk.appmanager.0000 : 73333 : 4545994176 : ERROR    : Error in AppManager
(venv) nbp-133-99:re.session.nbp-137-149.nbp.ruw.rutgers.edu.abdullahghani.018337.0000 abdullahghani$ cat pmgr.0000.log
1584375232.365 : pmgr.0000            : 73333 : 123145557733376 : ERROR    : [Callback]: pilot 'pilot.0000' failed (exit)
1584375232.366 : pmgr.0000            : 73333 : 123145557733376 : ERROR    : listener died
Traceback (most recent call last):
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/utils/zmq/pubsub.py", line 277, in _listener
    cb(t, m)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 320, in _state_sub_cb
    if not self._update_pilot(thing, publish=False):
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/pilot_manager.py", line 361, in _update_pilot
    self._pilots[pid]._update(pilot_dict)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 206, in _update
    else      : cb([self])
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/pilot/compute_pilot.py", line 152, in _default_state_cb
    ru.cancel_main_thread('int')
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/utils/threads.py", line 136, in cancel_main_thread
    if signame: signum = get_signal_by_name(signame)
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/utils/threads.py", line 228, in get_signal_by_name
(venv) nbp-133-99:re.session.nbp-137-149.nbp.ruw.rutgers.edu.abdullahghani.018337.0000 abdullahghani$ cat radical.entk.appmanager.0000.log
1584375232.439 : radical.entk.appmanager.0000 : 73333 : 4545994176 : ERROR    : Error in AppManager
Traceback (most recent call last):
  File "/Users/abdullahghani/venv/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 419, in run
    'ended in state %s' % res_alloc_state)
```

```
$ radical-stack

  python               : 3.7.6
  pythonpath           : 
  virtualenv           : /Users/abdullahghani/venv

  radical.entk         : 1.0.2
  radical.pilot        : 1.2.1
  radical.saga         : 1.2.0
  radical.utils        : 1.1.1
```

**Comment by andre-merzky** [comment]
Well, your error is included in what you pasted: `pilot 'pilot.0000' failed (exit)`.  So you probably want to check why the pilot failed.  Let us know if you need help with that!

**Comment by SrinivasMushnoori** [comment]
Following this: this is relevant to me.

**Comment by Abdullah-Ghani** [comment]
@SrinivasMushnoori this was resolved. Please check https://github.com/radical-cybertools/radical.pilot/issues/2079

Please let me know if you still have any issues.
