### ISSUE TITLE
RuntimeError: session create failed [Errno 111]

### ISSUE THREAD

**Issue by akashbanrutgers** [radical-cybertools/radical.entk#448]
Hi EnTK Developers, 

I am unable to execute one of the sample entk scripts (eop.py) on local host. I get the following error : 

################
(myenv) abanerjee@abanerjee-OptiPlex-990:~/Desktop/radical.entk/examples/simple$ python eop.py 
EnTK session: re.session.abanerjee-OptiPlex-990.abanerjee.018408.0003
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
                                                                             err
All components terminated
Traceback (most recent call last):
  File "eop.py", line 109, in <module>
    appman.run()
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/radical/entk/appman/appmanager.py", line 368, in run
    self._rmgr._submit_resource_request()
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 148, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/radical/pilot/session.py", line 255, in __init__
    % (self._dburl, e))
RuntimeError: session create failed [mongodb://repex_3:r3p3x_3@two.radical-project.org:27017/repex_3]: two.radical-project.org:27017: [Errno 111] Connection refused
#############

I have attached the verbose_logs.log file to this ticket. Further, I am not able to run the following command - 

 radical-pilot-fetch-logfiles re.session.abanerjee-OptiPlex-990.abanerjee.018408.0003

as I get the following error - 

#################################

(myenv) abanerjee@abanerjee-OptiPlex-990:~/Desktop/radical.entk/examples/simple$ radical-pilot-fetch-logfiles re.session.abanerjee-OptiPlex-990.abanerjee.018408.0003
Traceback (most recent call last):
  File "/home/abanerjee/myenv/bin/radical-pilot-fetch-logfiles", line 88, in <module>
    rpu.fetch_logfiles(sid=sid, dburl=dburl, src=src, tgt=tgt, access=access, skip_existing=skip)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/radical/pilot/utils/session.py", line 254, in fetch_logfiles
    _, db, _, _, _ = ru.mongodb_connect (dburl)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/radical/utils/misc.py", line 109, in mongodb_connect
    db.authenticate(user, pwd)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/pymongo/database.py", line 1471, in authenticate
    connect=True)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 751, in _cache_credentials
    writable_preferred_server_selector)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/pymongo/topology.py", line 231, in select_server
    address))
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/pymongo/topology.py", line 189, in select_servers
    selector, server_timeout, address)
  File "/home/abanerjee/myenv/local/lib/python2.7/site-packages/pymongo/topology.py", line 205, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: two.radical-project.org:27017: [Errno 111] Connection refused
#####################################################################

At this point , the radical sandbox is empty. Please guide me as to what I could do to fix this issue. 
[logfile.zip](https://github.com/radical-cybertools/radical.entk/files/4683008/logfile.zip)

Thank you for your help in advance.

Kind Regards,
Akash

**Comment by lee212** [comment]
Hi Akash,

The two.radical-project.org is currently offline due to security reasons. We will be replacing it shortly.

**Comment by SrinivasMushnoori** [comment]
@akashbanrutgers , I can give you the link to the MDB that I am using over email.
However, you'll need an RMQ as well. Let me see what I can do. This is not the same issue as we faced last time...

**Comment by akashban** [comment]
Thank you for your help Hyungro and Srinivas.

**Comment by SrinivasMushnoori** [comment]
@iparask Hi Giannis, has there been movement on the MDB/RMQ requests that @akashban made?
Thanks!

**Comment by SrinivasMushnoori** [comment]
Apologies: ignore the above. I think I do have the link. I will communicate to Akash. Thanks.

**Comment by shantenujha** [comment]
@SrinivasMushnoori  -- All OK ?

**Comment by SrinivasMushnoori** [comment]
@akashban , were you able to successfully run? 

Thanks!

**Comment by akashban** [comment]
Hi, 
The new MDB link works. However, since I am on python2.7, it does not not work. I am yet to move over to python3 and test if the EnTk examples work. Will keep you posted.

Thanks
Akash

**Comment by akashban** [comment]
Hi, 

I am able to run EnTK examples using the new MDB and RMQ links. Thank you all for your help.

Kind Regards,
Akash

**Comment by SrinivasMushnoori** [comment]
Excellent: that means this ticket can be closed. Cheers!
