### ISSUE TITLE
Cannot install from pip on Summit

### ISSUE THREAD

**Issue by wilkinson** [radical-cybertools/radical.entk#457]
This is definitely not expected, and I'm sure I'm doing something stupid, but I cannot get the `radical.entk` module to build.

On Summit:
```bash
$ mkdir ~/Workspace/bug-report-test
$ cd ~/Workspace/bug-report-test
$ rm -rf ~/.cache/pip/
$ module load python/3.7.0
$ python3 -m venv ./
$ source bin/activate
$ pip install --upgrade pip
$ pip install radical.entk
```

Output from the last command:
```
Collecting radical.entk
  Downloading radical.entk-1.4.1.post1.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 318 kB/s 
Collecting radical.utils
  Downloading radical.utils-1.4.0.tar.gz (152 kB)
     |████████████████████████████████| 152 kB 4.1 MB/s 
    ERROR: Command errored out with exit status 1:
     command: /autofs/nccs-svm1_home2/seanwilk/Workspace/bug-report-test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-uzv64afu/radical.utils/setup.py'"'"'; __file__='"'"'/tmp/pip-install-uzv64afu/radical.utils/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ixbf0jd2
         cwd: /tmp/pip-install-uzv64afu/radical.utils/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uzv64afu/radical.utils/setup.py", line 20, in <module>
        from setuptools import setup, find_namespace_packages
    ImportError: cannot import name 'find_namespace_packages' from 'setuptools' (/autofs/nccs-svm1_home2/seanwilk/Workspace/bug-report-test/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I'm not sure where to find the logs it's referring to. I apologize for what is almost certainly an idiot mistake on my part.

**Comment by mturilli** [comment]
Hi @wilkinson, that is indeed unexpected. On Summit, I use the following modules:
```
module load python/3.7.0
module load py-virtualenv/16.0.0
module load py-setuptools/40.4.3-py3
```

I just tested EnTK installation and it was successful:
```
Successfully built radical.entk radical.pilot radical.saga python-hostlist parse MarkupSafe
Installing collected packages: urllib3, idna, chardet, certifi, requests, apache-libcloud, parse, radical.saga, python-hostlist, ntplib, radical.pilot, pika, Pygments, alabaster, sphinxcontrib-jsmath, sphinxcontrib-qthelp, sphinxcontrib-serializinghtml, docutils, sphinxcontrib-htmlhelp, snowballstemmer, pytz, babel, imagesize, MarkupSafe, Jinja2, sphinxcontrib-devhelp, sphinxcontrib-applehelp, pyparsing, packaging, sphinx, radical.entk
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Pygments-2.6.1 alabaster-0.7.12 apache-libcloud-3.1.0 babel-2.8.0 certifi-2020.6.20 chardet-3.0.4 docutils-0.16 idna-2.9 imagesize-1.2.0 ntplib-0.3.4 packaging-20.4 parse-1.15.0 pika-0.13.0 pyparsing-2.4.7 python-hostlist-1.20 pytz-2020.1 radical.entk-1.4.1.post1 radical.pilot-1.4.1 radical.saga-1.4.0 requests-2.24.0 snowballstemmer-2.0.0 sphinx-3.1.1 sphinxcontrib-applehelp-1.0.2 sphinxcontrib-devhelp-1.0.2 sphinxcontrib-htmlhelp-1.0.3 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-qthelp-1.0.3 sphinxcontrib-serializinghtml-1.1.4 urllib3-1.25.9
```

Note that I created my environment with `virtualenv -p python3.7`

**Comment by wilkinson** [comment]
I can report a successful build using the modules you suggested. I'm not sure why they're necessary, but I can ask at OLCF for that part. Thanks!
