### ISSUE TITLE
Keeping directory structure in `shared_data`?

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#477]
Current implementation flattens/removes directory structure and stores data in one place. Does it require to keep the directory structure?

Example:
```
appman.shared_data = ["pdbs/adk-123.pdb", "examples/adk-123.pdb"]
-> uploads files to
staging_area/adk-123.pdb
```

**Comment by andre-merzky** [comment]
PS.: please always label tickets - thanks :-)

**Comment by mturilli** [comment]
@lee212 any follow up?

**Comment by mturilli** [comment]
@lee212 ping

**Comment by lee212** [comment]
I can confirm that this only happens under EnTK, and pilot preserves directory structure. EnTK places everything into `staging_area`, which I don't find under pilot though. I will look into the code and get back with a possible solution.

**Comment by iparask** [comment]
EnTK passes shared data through the pilot description [here](https://github.com/radical-cybertools/radical.entk/blob/devel/src/radical/entk/execman/rp/resource_manager.py#L160). However when I tried something like `appman.shared_data = ["test_shared/hello.txt > foo/hello.txt"] RP failed with the following message:

```
m' -e 'module load anaconda3'"]
1609881938.402 : pmgr_launching.0000  : 8516  : 139913797535488 : DEBUG    : out:
1609881938.402 : pmgr_launching.0000  : 8516  : 139913797535488 : DEBUG    : err: /bin/sh: 1: cannot create foo/hello.txt: Directory nonexistent

1609881938.402 : pmgr_launching.0000  : 8516  : 139913797535488 : ERROR    : bulk launch failed
Traceback (most recent call last):
  File "/home/iparask/miniconda3/envs/rct/lib/python3.9/site-packages/radical/pilot/pmgr/launching/default.py", line 560, in work
    self._start_pilot_bulk(resource, schema, pilots)
  File "/home/iparask/miniconda3/envs/rct/lib/python3.9/site-packages/radical/pilot/pmgr/launching/default.py", line 730, in _start_pilot_bulk
    raise RuntimeError('callout failed: %s' % cmd)
RuntimeError: callout failed: ln -s /home/iparask/EnTKUserGuide/test_shared/hello.txt > foo/hello.txt /tmp/rp_agent_tar_dir0k9vmlts/pilot.0000/staging_area/hello.txt
```

I think we need to document this correctly for users to know what to do and verify the correct use of the API.

@andre-merzky, does the pilot treat shared data from the description differently from the `stage_in` method?
