### ISSUE TITLE
pika connection issue

### ISSUE THREAD

**Issue by lee212** [radical-cybertools/radical.entk#480]
```
Traceback (most recent call last):
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/entk/execman/rp/task_manager.py", line 177, in _tmgr
    heartbeat_response(mq_channel)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/radical/entk/execman/rp/task_manager.py", line 113, in heartbeat_response
    mq_channel.basic_get(queue=self._hb_request_q)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2077, in basic_get
    self._basic_getempty_result.is_ready)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1292, in _flush_output
    *waiters)
  File "/ccs/home/hrlee/.conda/envs/workflow-2/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 477, in _flush_output
    result.reason_text)
pika.exceptions.ConnectionClosed: (320, 'No activity or too many missed heartbeats in the last 60 seconds')

```

this was generated while experiments were running on summit.

RMQ service used from 
```
RMQ_HOSTNAME=129.114.17.185
RMQ_PORT=5672
```

**Comment by mturilli** [comment]
@lee212 any follow up?

**Comment by lee212** [comment]
I suspect this issue was a system-related one-time failure, not particularly about entk. Let me close for now, and revisit later if this happens again.
