### ISSUE TITLE
MongoDB Radical Account Error

### ISSUE THREAD

**Issue by drawadiagram** [radical-cybertools/radical.entk#580]
Attempting to run entk using my MongoDB server Radical account, I get the following error
```sh
radical.entk.exceptions.EnTKError: session create failed [mongodb://mason:[password]@129.114.17.185:27017/mason]
```

, where `[password]` above is the string literal of my password. Please advise.

**Comment by nsanjrani** [comment]
Hello, I'm also experiencing the same problem although I think this is an issue with radical pilot

**Comment by akashban** [comment]
Hi @andre-merzky and @lee212 , I am experiencing the same issue: 
EnTK session: re.session.abanerjee-OptiPlex-990.abanerjee.018779.0000
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.abanerjee-OptiPlex-990.abanerjee.018779.0000]         \
database   : [mongodb://ab1628:****@129.114.17.185:27017/ab1628_pace]        err
All components terminated
Traceback (most recent call last):
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/pilot/session.py", line 178, in _initialize_primary
    cfg=self._cfg, log=self._log)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/pilot/db/database.py", line 49, in __init__
    self._mongo, self._db, _, _, _ = ru.mongodb_connect(str(dburl))
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/utils/misc.py", line 134, in mongodb_connect
    db.authenticate(user, pwd)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pymongo/database.py", line 1495, in authenticate
    connect=True)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pymongo/mongo_client.py", line 776, in _cache_credentials
    writable_preferred_server_selector)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pymongo/topology.py", line 243, in select_server
    address))
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pymongo/topology.py", line 200, in select_servers
    selector, server_timeout, address)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pymongo/topology.py", line 217, in _select_servers_loop
    (self._error_message(selector), timeout, self.description))
pymongo.errors.ServerSelectionTimeoutError: 129.114.17.185:27017: [Errno 111] Connection refused, Timeout: 30s, Topology Description: <TopologyDescription id: 60b66aa9e5297194b1e86596, topology_type: Single, servers: [<ServerDescription ('129.114.17.185', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('129.114.17.185:27017: [Errno 111] Connection refused')>]>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 146, in _submit_resource_request
    self._session = rp.Session(uid=self._sid)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/pilot/session.py", line 148, in __init__
    self._initialize_primary(dburl)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/pilot/session.py", line 193, in _initialize_primary
    dburl_no_passwd) from e
RuntimeError: session create failed [mongodb://ab1628:****@129.114.17.185:27017/ab1628_pace]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 428, in run
    self._rmgr._submit_resource_request()
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/entk/execman/rp/resource_manager.py", line 194, in _submit_resource_request
    raise EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: session create failed [mongodb://ab1628:****@129.114.17.185:27017/ab1628_pace]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/abanerjee/ve-entk/bin/pace", line 4, in <module>
    __import__('pkg_resources').run_script('pace==0.1', 'pace')
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/pace-0.1-py3.7.egg/EGG-INFO/scripts/pace", line 920, in <module>
  File "/home/abanerjee/ve-entk/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 459, in run
    raise EnTKError(ex) from ex


I do not have any other log files to show specifics. Please advice on what should be our next steps. 
Thanks
Akash

**Comment by andre-merzky** [comment]
Hi @akashban, @nsanjrani, @drawadiagram - sorry for the delayed response!

@lee212, @mturilli: do you happen to know what's up with `129.114.17.185`  - is that supposed to be open for projects to use or do we need to create accounts for it?

**Comment by mturilli** [comment]
Upon investigation, I found there was an issue with a spurious lock file in MongoDB. I fixed it and restarted the service. Could you try and see whether that fixed the issue?

**Comment by nsanjrani** [comment]
Working now, thanks!

**Comment by akashban** [comment]
Mine is also working. Thank you for your help.
