### ISSUE TITLE
log path unexpected

### ISSUE THREAD

**Issue by euhruska** [radical-cybertools/radical.entk#582]
importing radical.entk on Summit jupyter notebook fails with permission denied:
```
>>>import radical.entk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/entk/__init__.py", line 10, in <module>
    from . import execman
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/entk/execman/__init__.py", line 2, in <module>
    from . import rp
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/entk/execman/rp/__init__.py", line 3, in <module>
    from .task_manager     import TaskManager
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/entk/execman/rp/task_manager.py", line 21, in <module>
    from .task_processor   import create_td_from_task, create_task_from_rp
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/entk/execman/rp/task_processor.py", line 13, in <module>
    logger = ru.Logger('radical.entk.task_processor')
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/utils/logger.py", line 286, in __init__
    elif t in ['.']               : h = FSHandler("%s/%s.log" % (p, n))
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/site-packages/radical/utils/logger.py", line 174, in __init__
    logging.FileHandler.__init__(self, target)
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/logging/__init__.py", line 1146, in __init__
    StreamHandler.__init__(self, self._open())
  File "/ccs/proj/chm179/eh22/entk4/lib/python3.9/logging/__init__.py", line 1175, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '//radical.entk.task_processor.log'
```
I think it should not need a log file path with extra permissions..
```
  python               : /ccs/proj/chm179/eh22/entk4/bin/python3
  pythonpath           : 
  version              : 3.9.4
  virtualenv           : /ccs/proj/chm179/eh22/entk4

  radical.analytics    : ?
  radical.entk         : ?
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.6
  radical.saga         : 1.6.6
  radical.utils        : 1.6.6
```
conda list gives:``` radical-entk              1.6.5                    pypi_0  ```
Reverting to entk 1.6.0 fixes this issue.

**Comment by andre-merzky** [comment]
Hi @euhruska - this issue should be fixed with merging #584 - the next release of RE (upcoming this week) will contain the fix.  Thanks for your patience!
