### ISSUE TITLE
`examples/simple/eop.py|poe.py` are broken

### ISSUE THREAD

**Issue by mturilli** [radical-cybertools/radical.entk#587]
We should check/test all the examples and be sure that they work.

**Comment by mturilli** [comment]
Here the error:
```
$ ./eop.py
EnTK session: re.session.js-17-185.jetstream-cloud.org.mturilli.018824.0002
Creating AppManagerSetting up RabbitMQ system                                 ok
Traceback (most recent call last):
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 558, in _setup_mqs
    mq_connection = pika.BlockingConnection(self._rmq_conn_params)
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 377, in __init__
    self._process_io_for_connection_setup()
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 417, in _process_io_for_connection_setup
    self._open_error_result.is_ready)
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 469, in _flush_output
    raise maybe_exception
pika.exceptions.ProbableAuthenticationError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./eop.py", line 90, in <module>
    password=password)
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 128, in __init__
    self._setup_mqs()
  File "/home/mturilli/ve-entk/lib/python3.7/site-packages/radical/entk/appman/appmanager.py", line 592, in _setup_mqs
    raise ree.EnTKError(ex) from ex
radical.entk.exceptions.EnTKError: (403, 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.')
```

`examples/user_guide/get_started.py` works with the same stack and env variables.

**Comment by lee212** [comment]
The `eop.py` and `poe.py` are recently updated and I just ran the test on radical VM:

```
(devel) hrlee@js-17-185:~/git/radical.entk/examples/simple$ ./eop.py
EnTK session: re.session.js-17-185.jetstream-cloud.org.hrlee.018824.0003
Creating AppManagerSetting up RabbitMQ system                                 ok
                                                                              ok
Validating and assigning resource manager                                     ok
Setting up RabbitMQ system                                                   n/a
new session: [re.session.js-17-185.jetstream-cloud.org.hrlee.018824.0003]      \
database   : [mongodb://ci-test:****@129.114.17.185/ci-test]                  ok
create pilot manager                                                          ok
submit 1 pilot(s)
        pilot.0000   local.localhost           1 cores       0 gpus           ok


All components created
create task managerUpdate: pipeline.0003 state: SCHEDULING
Update: pipeline.0003.stage.0009 state: SCHEDULING
Update: pipeline.0003.stage.0009.task.0009 state: SCHEDULING
...
```

Maybe can you share your `eop.py` or make sure it is up-to-date? The latest version will use 
```
RMQ_PASSWORD
RMQ_USERNAME
RMQ_HOSTNAME
RMQ_PORT
```
and this PLAIN authentication error is usually fixed with these env variables and the latest example files.

**Comment by drawadiagram** [comment]
I get this error with stack as follows:
>   python               : /home/mason/dutt_lab/pace/pace_env/bin/python3
  pythonpath           : 
  version              : 3.8.10
  virtualenv           : /home/mason/dutt_lab/pace/pace_env

  radical.entk         : 1.6.5
  radical.gtod         : 1.5.0
  radical.pilot        : 1.6.6
  radical.saga         : 1.6.6
  radical.utils        : 1.6.6

**Comment by lee212** [comment]
@drawadiagram, EnTK, and RCT have been updated recently, and the latest version of EnTK is 1.6.7. Can you refresh your stack and run this example again if it resolves the `PLAIN` auth error?
`pip install --upgrade radical.entk radical.pilot radical.utils radical.saga` will do the update .

**Comment by drawadiagram** [comment]
Updated stack and that resolves the issue for me. Thanks @lee212 ! May want @mturilli to confirm as well.
